### ISSUE TITLE
Failed to install apk /var/folders/ly/n11h40q11db4p9_2mzbcznk40000gq/T/maestro-app7270736821262783708.apk: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by GainLee** [mobile-dev-inc/maestro#354] opened 2022-11-04 03:23 UTC
When run the sample, get the flowing exception
After upgraded maestro, still get the exception.

==> Upgrading mobile-dev-inc/tap/maestro
  1.11.3 -> 1.11.4

OS: MacOS 12.4

```
java.io.IOException: Failed to install apk /var/folders/ly/n11h40q11db4p9_2mzbcznk40000gq/T/maestro-app7270736821262783708.apk: Broken pipe (Write failed)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:421)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:401)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:73)
	at maestro.Maestro$Companion.android(Maestro.kt:407)
	at maestro.Maestro$Companion.android$default(Maestro.kt:405)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:40)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:63)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:31)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:97)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:81)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:419)
	... 15 more
```

**Comment by Leland-Takamine** [comment] 2022-11-04 03:26
Hey  @GainLee what version of Android are you running?

**Comment by GainLee** [comment] 2022-11-04 03:30
> 

Android 13 and Android 11

**Comment by GainLee** [comment] 2022-11-11 01:49
> Hey @GainLee what version of Android are you running?

Is anything updated? @Leland-Takamine

**Comment by Leland-Takamine** [comment] 2022-11-28 20:58
Bumped this to high priority internally. We'll dive deeper on this soon

**Comment by ouchadam** [comment] 2022-12-20 14:22
also seeing the same issue on an Intel mac with `1.17.4`

- Invoking adb directly works fine `adb install /path/to/test/.apk`
- M1 macbooks with similar environment work fine

<details>

```
java.io.IOException: Failed to install apk /path/to/test/apk: Broken pipe (Write failed)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:487)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:467)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:82)
	at maestro.Maestro$Companion.android(Maestro.kt:511)
	at maestro.Maestro$Companion.android$default(Maestro.kt:509)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:40)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:84)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:119)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at [java.net](http://java.net/).SocketOutputStream.socketWrite0(Native Method)
	at [java.net](http://java.net/).SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at [java.net](http://java.net/).SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:81)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:485)
```

</details>

**Comment by vibin** [comment] 2023-01-01 18:21
I'm facing the same issue in AWS Device farm, except for the "Write failed" part:

Maestro installed using: `curl -Ls "https://get.maestro.mobile.dev" | bash`

From the logs below, it's clear that `adb devices`, `install` and `uninstall` commands are working fine

<details>
<summary>Logs (click to expand)</summary>
<pre>
[DeviceFarm] export PATH="$PATH":"$HOME/.maestro/bin"
[DeviceFarm] adb install $DEVICEFARM_APP_PATH
Success
[DeviceFarm] adb uninstall com.meesho.supply
Success
[DeviceFarm] echo "Navigate to test package directory"
Navigate to test package directory
[DeviceFarm] cd $DEVICEFARM_TEST_PACKAGE_PATH
[DeviceFarm] echo "Start Maestro flow test"
Start Maestro flow test
[DeviceFarm] adb devices
List of devices attached
28161FDH200EGH	device

[DeviceFarm] $HOME/.maestro/bin/maestro test flow-2.yml
Running on 28161FDH200EGH

java.io.IOException: Failed to install apk /tmp/maestro-app5950479976002925136.apk: Broken pipe
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:487)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:467)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:82)
	at maestro.Maestro$Companion.android(Maestro.kt:498)
	at maestro.Maestro$Companion.android$default(Maestro.kt:496)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:43)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:84)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:40)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:119)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:81)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:485)
	... 16 more
</pre>
</details>

**Comment by UnluckyY1** [comment] 2023-01-01 23:45
I had the same issue on Ubuntu, I managed to fix it by updating ADB to the last version.

**Comment by vibin** [comment] 2023-01-02 04:02
> I had the same issue on Ubuntu, I managed to fix it by updating `ADB` to the last version.

@UnluckyY1 Which version of ADB are you using now?

**Comment by axelniklasson** [comment] 2023-05-12 08:10
Hi there folks! Could you try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!

**Comment by axelniklasson** [comment] 2023-05-12 08:34
Relates to #559

**Comment by vibin** [comment] 2023-05-20 18:22
Tried 1.28.0 on AWS device farm today - this issue seems to be resolved. Thanks!

**Comment by axelniklasson** [comment] 2023-05-30 11:25
Glad that it works for you @vibin!

Closing this one out as further investigation will be tracked in #559

**Closed by axelniklasson** 2023-05-30 11:25 UTC
Labels: bug, android, needs-information

**Comment by tomoakley** [comment] 2023-06-16 11:11
Hi @axelniklasson, I'm still experiencing this running Maestro 1.28.0 on AWS Device Farm:
```
[DEVICEFARM] Setting up your device. This usually takes 2-3 minutes.
[DEVICEFARM] ########### Start executing testspec ###########
 
 
[DEVICEFARM] ########### Entering phase install ###########
 
[DeviceFarm] curl -Ls "https://get.maestro.mobile.dev" | bash
* Create distribution directories...
* Downloading...

##                                                                         3.8%
######                                                                     8.4%
#########                                                                 13.0%
############                                                              17.6%
###############                                                           22.2%
###################                                                       26.9%
######################                                                    31.4%
#########################                                                 36.0%
#############################                                             40.6%
################################                                          45.2%
###################################                                       49.8%
#######################################                                   54.5%
##########################################                                59.0%
#############################################                             63.6%
#################################################                         68.2%
####################################################                      72.8%
#######################################################                   77.4%
###########################################################               82.0%
##############################################################            86.6%
#################################################################         91.2%
####################################################################      95.8%
######################################################################## 100.0%
* Checking archive integrity...
* Extracting archive...
* Copying archive contents...
* Cleaning up...

Attempt update of interactive bash profile on regular UNIX...
Adding maestro to your PATH in /home/device-farm/.bashrc
Adding maestro to your PATH in /home/device-farm/.zshrc

Installation was successful!
Please open a new terminal OR run the following in the existing one:

    export PATH="$PATH":"$HOME/.maestro/bin"

Then run the following command:

    maestro

Welcome to Maestro!
[DeviceFarm] export PATH="$PATH":"$HOME/.maestro/bin"
[DeviceFarm] echo YXBwSWQ6IGNvbS50b3RhbGx5bW9uZXkuYWNjb3VudAotLS0KLSBsYXVuY2hBcHAKLSB0YXBPbjoKICAgIGlkOiAib25ib2FyZGluZ0hvbWVwYWdlTG9naW5CdXR0b24iCi0gdGFwT246ICJZb3VyIGVtYWlsIGFkZHJlc3MiCi0gaW5wdXRUZXh0OiAiYXBwc3RvcmVAYXBwbGUudG90YWxseW1vbmV5LmNvbSIKLSB0YXBPbjogIllvdXIgcGFzc3dvcmQiCi0gaW5wdXRUZXh0OiAiVGVzdGluZ0BwcDEiCi0gImhpZGVLZXlib2FyZCIKLSB0YXBPbjoKICAgIGlkOiAibG9naW5QYWdlTG9naW5CdXR0b24iCi0gdGFwT246CiAgICBpZDogImFuZHJvaWQ6aWQvYXV0b2ZpbGxfc2F2ZV9ubyIKLSBhc3NlcnRWaXNpYmxlOiAiSGkgS3VsYmlyIgo= | base64 -d > test.yml
[DeviceFarm] cat test.yml
appId: com.totallymoney.account
---
- launchApp
- tapOn:
    id: "onboardingHomepageLoginButton"
- tapOn: "Your email address"
- inputText: "useremail@email.com"
- tapOn: "Your password"
- inputText: "password"
- "hideKeyboard"
- tapOn:
    id: "loginPageLoginButton"
- tapOn:
    id: "android:id/autofill_save_no"
- assertVisible: "Hi <name>"
 
[DEVICEFARM] ########### Entering phase pre_test ###########
 
 
[DEVICEFARM] ########### Entering phase test ###########
 
[DeviceFarm] maestro test test.yml
Running on RFCW11RBRXY

java.io.IOException: Failed to install apk /tmp/maestro-app3920492771901951187.apk: Broken pipe
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:761)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:741)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:92)
	at maestro.Maestro$Companion.android(Maestro.kt:565)
	at maestro.cli.session.MaestroSessionManager.createAndroid(MaestroSessionManager.kt:270)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:151)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:49)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:81)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:80)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:80)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:126)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:44)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:136)
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:194)
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:81)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:759)
	... 23 more

I guess the key difference is decoding the test yaml from base64 as @almouro did in #425, but as you can see I outputted the contents of test.yml and it seems fine. I added `adb install $DEVICEFARM_TEST_PACKAGE_PATH` and then uninstalled it after and both worked fine. 

The same test file runs perfectly on my real Android device.
Should I open a new issue, post in #559 or keep here?

**Comment by tomoakley** [comment] 2023-06-16 18:59
I realised AWS Device Farm was using Node 10 or 11 - updating to Node 16 via nvm on the AWS DF runner now gives me the error that @almouro had on #425:
```
java.io.IOException: Failed to install apk /tmp/maestro-app4823397864414925240.apk: Install failed: Package manager (package)
```
