### ISSUE TITLE
[Bug] Running the test on Windows WSL2 produce java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by landarskiy** [mobile-dev-inc/maestro#595] opened 2023-01-12 10:13 UTC
After run  `maestro test maestro_test/flow.yaml` on WSL2 in console appears
```
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/java.net.Socket.<init>(Socket.java:454)
        at java.base/java.net.Socket.<init>(Socket.java:231)
        at dadb.adbserver.AdbServer.listDadbs(AdbServer.kt:67)
        at dadb.adbserver.AdbServer.listDadbs$default(AdbServer.kt:60)
        at dadb.Dadb$Companion.list(Dadb.kt:244)
        at dadb.Dadb$Companion.list$default(Dadb.kt:243)
        at maestro.cli.device.DeviceService.listAndroidDevices(DeviceService.kt:151)
        at maestro.cli.device.DeviceService.listDevices(DeviceService.kt:147)
        at maestro.cli.device.DeviceService.listConnectedDevices(DeviceService.kt:137)
        at maestro.cli.device.PickDeviceInteractor.pickDeviceInternal(PickDeviceInteractor.kt:33)
        at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:14)
        at maestro.cli.session.MaestroSessionManager.selectDevice(MaestroSessionManager.kt:87)
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:48)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:97)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:39)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:119)
```
adb commands work correctly e.g. `adb devices` and `adb install` executed without problems.
One detail that not covered in a report: I use windows adb that was installed by the following instruction:

if we installed adb in windows and the path is /mnt/c/platform-tools/adb.exe
the WSL2 adb install at /usr/bin/adb
let change adb to adb_bk and set ln -s to link adb.exe
`sudo mv /usr/bin/adb /usr/bin/adb_bk`
`sudo ln -s /mnt/c/platform-tools/adb.exe /usr/bin/adb`
now we can use adb and work at bash script

Logs:
[2023-01-12_105542.zip](https://github.com/mobile-dev-inc/maestro/files/10400446/2023-01-12_105542.zip)

**Comment by axelniklasson** [comment] 2023-05-03 14:17
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on our [Windows installation docs](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:17 UTC
