### ISSUE TITLE
[Feature Request] Suggestion to improve the visualization of the Views hierarchy in Maestro Studio

### ISSUE THREAD

**Issue by jonatasPassosCarreiro** [mobile-dev-inc/maestro#1590] opened 2023-11-15 18:09 UTC
Currently, in Maestro Studio's default viewer, it is not possible to see the hierarchy of views, when I have two views representing the same component, if Maestro suggests the view that has the AccessibilityLabel, I can't see that I have another view that contains the component's text. Only by searching for the id/text in the search input can I see that I have two views. And even the search input, which gives feedback on the desired search in the side tab, doesn't show me the hierarchy of views in Maestro Studio like Appium does. I can only see the hierarchy of views in a structured way using the maestro hierarchy and maestro query commands. It would be interesting to improve this in Maestro Studio. But Maestro Studio is more faithful to the attributes of the elements than Appium (id is id and label is label), Appium mixes up the attributes and that's not good.

**Comment by bartekpacia** [comment] 2024-07-18 10:19
Hello @jonatasPassosCarreiro, thank you for sharing this feature request with us. It seems to me that it's a duplicate of #1031, so let's use that issue for tracking. This one, I'm going to close it.

**Closed by bartekpacia** 2024-07-18 10:19 UTC
Labels: enhancement
