### ISSUE TITLE
App doesn't record tap on bottom nav item, but maestro marks as successful

### ISSUE THREAD

**Issue by sanskar10100** [mobile-dev-inc/maestro#162] opened 2022-09-12 06:36 UTC
Jetpack Compose app, code for the UI component in question:
```kotlin
BottomNavigationItem(
            selected = selectedItem == Screen.FAVORITES,
            onClick = { if (selectedItem != Screen.FAVORITES) navController.navigate(R.id.favoritesFragment) },
            icon = {
                Icon(Icons.Filled.Favorite, contentDescription = null)
            },
            label = { Text("Favorites", modifier = Modifier.semantics { contentDescription = "Favorites" }) }
        )
```

Test yaml:
```
appId: dev.sanskar.pokedex
---
- launchApp
- tapOn: "Favorites"
```

Observed Behavior:
https://user-images.githubusercontent.com/22092047/189587494-6662100b-77cb-48c6-81f6-17d3ca314e37.mp4

Even tried with a test tag (#101). Modified UI Code:
```kotlin
BottomNavigationItem(
            selected = selectedItem == Screen.FAVORITES,
            onClick = { if (selectedItem != Screen.FAVORITES) navController.navigate(R.id.favoritesFragment) },
            icon = {
                Icon(Icons.Filled.Favorite, contentDescription = null)
            },
            label = {
                Text(
                    "Favorites",
                    modifier = Modifier
                        .testTag("favorites_bottom_nav")
                        .semantics { testTagsAsResourceId = true
                        }
                ) }
        )
```

Test yaml:
```
appId: dev.sanskar.pokedex
---
- launchApp
- tapOn:
    id: "favorites_bottom_nav"
```

The same behavior is observed. 

**In both cases, I can see `"text" : "Favorites",` in the output of `maestro hierarchy`**.
Here's the hierarchy output for the first case:
[hiearchy.txt](https://github.com/mobile-dev-inc/maestro/files/9545252/hiearchy.txt)

**Comment by dmitry-zaitsev** [comment] 2022-09-12 09:44
Note that Maestro will try to tap the Favorites button as soon as it sees it, which in this case might be during the loading phase. Could that perhaps be the reason? What happens if you press the "Favorites" button manually while the content is loading? Judging by the fact that test succeeded, it could indeed find the view, so the issue is somewhere else.

**Comment by sanskar10100** [comment] 2022-09-12 10:41
[default behavior.webm](https://user-images.githubusercontent.com/22092047/189634035-10467ff4-2863-48b2-83aa-b2a1656c5600.webm)

Even if the favorites item is clicked during the loading phase, the fragment would switch at least. That wasn't the case here.

**Comment by javalnanda** [comment] 2023-01-25 07:39
@sanskar10100 If you are trying to use `testTag`, verify that `testTagsAsResourceId` semantics is enabled.
https://developer.android.com/jetpack/compose/testing#uiautomator-interop

I faced the same issue and turned out that I missed enabling this semantic property for the composable subtree.

**Comment by axelniklasson** [comment] 2023-05-03 13:27
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 13:27 UTC
Labels: question
