### ISSUE TITLE
[react-native] iOS view hierachy contains unexpected text label duplications

### ISSUE THREAD

**Issue by AlexanderEggers** [mobile-dev-inc/maestro#626] opened 2023-01-17 11:54 UTC
When inspecting the react-native UI of my application via the mastro CLI, I noticed that tabs contain an unexpected structure on iOS compared to Android.

iOS:
```
{
  "attributes" : {
   "text" : "Payments Payments",
   "resource-id" : "tab-0",
   "bounds" : "[0,50][195,98]"
  },
  "children" : [ ],
  "enabled" : true
 }
```

Android:
```
{
   "attributes" : {
    "text" : "Payments",
    "resource-id" : "",
    "clickable" : "false",
    "bounds" : "[311,107][524,173]",
     "enabled" : "true",
     "focused" : "false",
     "checked" : "false",
     "selected" : "false"
},
```

I understand why the resource-id is not set on Android (part of a parent element) but I noticed that iOS has the text label “Payments Payments” which is unexpected. I am wondering if that is actually an issue with the maestro tooling or if that has something to do how react-native is rendered on iOS side at that point.

Issue was orginally raised on Slack via https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1673955971189939

**Comment by axelniklasson** [comment] 2023-05-03 14:21
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on iOS since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:21 UTC
