### ISSUE TITLE
[Feature Request] Assert Drawable Images

### ISSUE THREAD

**Issue by boranfrkn** [mobile-dev-inc/maestro#1491] opened 2023-09-27 08:47 UTC
I want to assert drawable images. Sometimes we don't/can't use selectors and refactoring where we don't use them can be a lot of effort. It would be nice to assert images instead. 
If this is possible it would be a really necessary feature.

```
tapOn: favoriteButton
assertVisibleDrawable: R.drawable.favorite_icon // I don't know how to add images in iOS
```

**Comment by bartekpacia** [comment] 2024-07-27 22:18
seems to be a duplicate of #1796

**Closed by bartekpacia** 2024-07-27 22:18 UTC
Labels: enhancement
