### ISSUE TITLE
I can't open Studio. 1.18.3 MacOS 13.0.1

### ISSUE THREAD

**Issue by alesav** [mobile-dev-inc/maestro#564] opened 2023-01-03 16:21 UTC
I can't open Maestro Studio. I just installed the latest Maestro using Homebrew and typed "maestro studio". MacOS 13.0.1

java.util.concurrent.TimeoutException: Couldn't close Maestro iOS driver due to gRPC timeout
	at ios.idb.IdbIOSDevice.close(IdbIOSDevice.kt:507)
	at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:61)
	at maestro.cli.device.DeviceService.startIdbCompanion(DeviceService.kt:102)
	at maestro.cli.device.DeviceService.prepareDevice(DeviceService.kt:72)
	at maestro.cli.device.PickDeviceInteractor.pickDevice(PickDeviceInteractor.kt:26)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:38)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:37)
	at maestro.cli.command.StudioCommand.call(StudioCommand.kt:19)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:119)

**Comment by artem888** [comment] 2023-01-25 12:36
hey @alesav ! thanks for your feedback. the issue is resolved with maestro version 1.20.0. please [update your local cli](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) in order to make it fixed

https://github.com/mobile-dev-inc/maestro/pull/652

**Closed** 2023-01-25 12:37 UTC
