### ISSUE TITLE
[iOS-SwuiftUI] Maestro are tapping over one unexpected field.

### ISSUE THREAD

**Issue by dabrinnajera** [mobile-dev-inc/maestro#729] opened 2023-02-02 21:35 UTC
When I have run the Maestro test or Maestro Studio, my device are tapping over one unexpected field, and when I try the same steps manually the app runs well.

The steps are so much easy:
<img width="519" alt="Screen Shot 2023-02-02 at 15 34 40" src="https://user-images.githubusercontent.com/88212032/216454744-26774e54-2086-49c5-bec6-fddbf66ed356.png">

**Comment by Leland-Takamine** [comment] 2023-05-03 14:14
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by Leland-Takamine** 2023-05-03 14:14 UTC
