### ISSUE TITLE
Failed to install apk while running Tests at `maestro.drivers.AndroidDriver.install(AndroidDriver.kt:761)`

### ISSUE THREAD

**Issue by bipin-k** [mobile-dev-inc/maestro#1073] opened 2023-05-15 15:01 UTC
**Describe the bug**
Unable to execute the test script as expected.

**To Reproduce**
1. Connect Mobile device and make sure the app is pre-installed,
2. Run `maestro test mpl.yaml`
3. The Flow fails at ...

```
➜  ~ maestro test Desktop/mpl.yaml
Running on 2ae9c69c

java.io.IOException: Failed to install apk /var/folders/vz/4l9pz0yx3v30kt_xwwk1ql1w0000gp/T/maestro-app5230371881326634187.apk: Install failed:
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:761)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:741)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:92)
	at maestro.Maestro$Companion.android(Maestro.kt:557)
	at maestro.cli.session.MaestroSessionManager.createAndroid(MaestroSessionManager.kt:270)
	at maestro.cli.session.MaestroSessionManager.createMaestro(MaestroSessionManager.kt:151)
	at maestro.cli.session.MaestroSessionManager.access$createMaestro(MaestroSessionManager.kt:49)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:81)
	at maestro.cli.session.MaestroSessionManager$newSession$session$1.invoke(MaestroSessionManager.kt:80)
	at maestro.cli.db.KeyValueStore.withExclusiveLock(KeyValueStore.kt:37)
	at maestro.cli.session.SessionStore.withExclusiveLock(SessionStore.kt:74)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:80)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:57)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
Caused by: java.io.IOException: Install failed:
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:85)
	at dadb.adbserver.AdbServerDadb.install(AdbServer.kt:118)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:759)
	... 23 more
```

**Expected behavior**
Test Script should be executed successfully.

**Environment information**
- Maestro version [e.g. v1.2.3] - 1.27.0
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome] - v10
- Framework: [Native iOS/Android, Flutter, React Native, etc] - React Native
- Device model and OS version: [e.g. iPhone6] - OnePlus 5T - OnePlus A5010
- Simulator, emulator or physical device - Physical Device
- Host [e.g. Mac M1, Windows, Linux, etc] - Mac Intel

**Test Script**
```
appId: com.mpl.androidapp
---
- launchApp
- waitForAnimationToEnd:
    timeout: 60000
- tapOn: "Set Language to English"
```

[2023-05-15_195352.zip](https://github.com/mobile-dev-inc/maestro/files/11479058/2023-05-15_195352.zip)
[2023-05-15_195840.zip](https://github.com/mobile-dev-inc/maestro/files/11479059/2023-05-15_195840.zip)
[2023-05-15_200743.zip](https://github.com/mobile-dev-inc/maestro/files/11479061/2023-05-15_200743.zip)
[2023-05-15_201019.zip](https://github.com/mobile-dev-inc/maestro/files/11479062/2023-05-15_201019.zip)
[2023-05-15_202423.zip](https://github.com/mobile-dev-inc/maestro/files/11479063/2023-05-15_202423.zip)
[2023-05-15_202619.zip](https://github.com/mobile-dev-inc/maestro/files/11479064/2023-05-15_202619.zip)

**Comment by axelniklasson** [comment] 2023-05-16 09:14
Relates to #829

**Comment by igorsmotto** [comment] 2023-05-16 14:48
Duplicate of https://github.com/mobile-dev-inc/maestro/issues/829

**Closed by igorsmotto** 2023-05-16 14:48 UTC
Labels: bug, android

**Comment by laxkarparas1** [comment] 2024-01-12 08:48
wireless debugging works well and if we are debugging through wired connect physical device it throws error
