### ISSUE TITLE
TextField Label not found in Flutter 3.7.0

### ISSUE THREAD

**Issue by SebastianKlaiber** [mobile-dev-inc/maestro#671] opened 2023-01-25 09:40 UTC
After updating my project to the newest flutter version, maestro couldn't find the TextField label as well as the Semantics.
With Flutter 3.3.10 everything was working fine. Therefore, not sure if it is related to maestro or flutter. 

![image](https://user-images.githubusercontent.com/59142/214529053-e9193c09-e9b9-4d30-a548-894b3a9a49a0.png)

``` dart
Semantics(
          label: context.localization.common_email_field_label,
          child: TextField(
            key: const Key('loginForm_usernameInput_textField'),
            controller: _controller,
            keyboardType: TextInputType.emailAddress,
            textInputAction: TextInputAction.next,
            autofillHints: const [AutofillHints.email],
            autocorrect: false,
            decoration: InputDecoration(
              labelText: context.localization.common_email_field_label,
              errorText: _emailError(email),
            ),
            onEditingComplete: widget.onEditingComplete,
          ),
        );
```

**Comment by SebastianKlaiber** [comment] 2023-01-26 06:25
It's working again with the latest version.

**Comment by amanjeetsingh150** [comment] 2023-01-26 06:32
Hey @SebastianKlaiber may I know which version now you use where it correctly works and what was the previous one?

**Comment by SebastianKlaiber** [comment] 2023-01-26 06:34
Sorry. It was just working with a filled out textfield and not with the label.

**Comment by SebastianKlaiber** [comment] 2023-01-26 06:35
![image](https://user-images.githubusercontent.com/59142/214772295-b79f908a-70a6-4ca5-8d4d-c2509009469d.png)
![image](https://user-images.githubusercontent.com/59142/214772388-7aa6f61a-e42f-4e1e-ab64-cf3475af96e7.png)

**Comment by JigneshWorld** [comment] 2023-01-27 12:48
Reference: Added this on Flutter Repo
https://github.com/flutter/flutter/issues/119326

**Comment by JigneshWorld** [comment] 2023-02-03 05:14
To access the field this way, some work is required on maestro tooling. 
https://github.com/mobile-dev-inc/maestro/issues/730

**Comment by yasht01** [comment] 2023-03-17 11:28
Any update to this issue? It still persists on version `3.7.7`

**Comment by axelniklasson** [comment] 2023-05-03 14:44
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on [Flutter support in Maestro ](https://maestro.mobile.dev/platform-support/flutter)since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:44 UTC
