### ISSUE TITLE
Android driver timeout

### ISSUE THREAD

**Issue by ebarrenechea** [mobile-dev-inc/maestro#281] opened 2022-10-17 14:17 UTC
I work with a custom made device which has some fairly modest hardware specs which keeps timing out whenever I try to run a test. 
```
java.util.concurrent.TimeoutException: Maestro Android driver did not start up in time
	at maestro.drivers.AndroidDriver.awaitLaunch(AndroidDriver.kt:119)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:83)
``` 

Changing the timeout fixed this issue for us. Is there any specific reason why `SERVER_LAUNCH_TIMEOUT_MS ` is kept at 5s? Could we bump it up to 10s instead? Another option would be to accept the timeout as a command argument and fallback to the built-in one if not specified by the user.

**Comment by carlosmuvi-stripe** [comment] 2022-10-17 16:49
I think this is a duplicate of this closed (but still ongoing) issue - https://github.com/mobile-dev-inc/maestro/issues/144

**Comment by simon-gilmurray** [comment] 2022-10-20 13:41
Also encountering this issue trying to get Android tests up and running on CI.

**Comment by amanjeetsingh150** [comment] 2022-11-04 09:03
@carlosmuvi-stripe @simon-gilmurray @ebarrenechea we have tweaked the timeout to be 15 seconds which should give enough time to start the maestro server. Let me know if this works for you 🙌 

Feel free to reopen if this is still an issue!

**Closed by amanjeetsingh150** 2022-11-04 09:03 UTC

**Comment by simon-gilmurray** [comment] 2022-11-04 09:37
Thanks @amanjeetsingh150 unfortunately this still seems to be causing the same issue on our CI using a Genymotion emulator. I need to do some more investigating in to why as I can see from a screenshot that the emulator seems to be displaying a system popup that could potentially be interfering.

**Comment by ebarrenechea** [comment] 2022-11-04 13:49
@amanjeetsingh150 version 1.11.4 works great with our custom device, thanks! 🙌
