### ISSUE TITLE
[Feature Request] New commands

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1589] opened 2023-11-15 14:20 UTC
**Is your feature request related to a problem? Please describe.**

1) `maestro upgrade
`

it would automatically update the new version: `curl -Ls "https://get.maestro.mobile.dev" | bash`

In case your version is updated to the latest.
`Congrats! You're already on the latest version of Maestro (which is v1.34.1)
`

2)
`maestro update
`
It should tell you if there is a more up-to-date version than yours.

**Comment by bartekpacia** [comment] 2024-07-12 23:29
Hey, thanks for creating an issue. This sounds like something that should be a responsibility of a package manager. So I'll consider it a duplicate of #1513

**Closed by bartekpacia** 2024-07-12 23:29 UTC
Labels: enhancement
