### ISSUE TITLE
v1.24.0 Throws an error when running a flow

### ISSUE THREAD

**Issue by gumil** [mobile-dev-inc/maestro#877] opened 2023-03-08 16:07 UTC
Just by running a flow with a simple `launchApp` command gives the following error:
```
org.mozilla.javascript.EvaluatorException: missing ; before statement (inline-script#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
	at org.mozilla.javascript.Parser.addError(Parser.java:257)
	at org.mozilla.javascript.Parser.reportError(Parser.java:336)
	at org.mozilla.javascript.Parser.reportError(Parser.java:327)
	at org.mozilla.javascript.Parser.reportError(Parser.java:320)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1279)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1254)
	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
	at org.mozilla.javascript.Parser.parse(Parser.java:632)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.JsEngine.evaluateScript(JsEngine.kt:86)
	at maestro.js.JsEngine.evaluateScript$default(JsEngine.kt:58)
	at maestro.orchestra.Orchestra.defineVariablesCommand(Orchestra.kt:256)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:193)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:141)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:73)
	at maestro.cli.runner.TestSuiteInteractor.runFlow(TestSuiteInteractor.kt:141)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:72)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:34)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:142)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

**Comment by erykrutkowski** [comment] 2023-03-09 09:01
I guess that is similar issue to mine:
https://github.com/mobile-dev-inc/maestro/issues/879
the only difference seems to be that it broke on different char and that it is missing instead of illegal. I suggest take a look on system env variables - use `printenv` or `set` to see all system env variables.

**Comment by moaaz-zenbusiness** [comment] 2023-03-14 20:10
i face the same issue with version 1`.25.0` as well  Seems this is related to newer versions, when i downgrade version to 1.21.3 it works fine

**Comment by latorante** [comment] 2023-04-05 11:14
Hey hey :wave: I have the same issues. Has anybody found a way to fix this?

**Comment by carlosmuvi-stripe** [comment] 2023-04-05 17:02
seeing a slightly different `EvaluatorException` failure as well in 1.25.0. Downgrading also works:

```
org.mozilla.javascript.EvaluatorException: unterminated string literal (inline-script#1)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:79)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:66)
	at org.mozilla.javascript.Parser.addError(Parser.java:257)
	at org.mozilla.javascript.Parser.addError(Parser.java:228)
	at org.mozilla.javascript.Parser.addError(Parser.java:223)
	at org.mozilla.javascript.TokenStream.getToken(TokenStream.java:942)
	at org.mozilla.javascript.Parser.peekToken(Parser.java:396)
	at org.mozilla.javascript.Parser.assignExpr(Parser.java:2276)
	at org.mozilla.javascript.Parser.variables(Parser.java:2128)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1197)
	at org.mozilla.javascript.Parser.statement(Parser.java:1104)
	at org.mozilla.javascript.Parser.parse(Parser.java:632)
	at org.mozilla.javascript.Parser.parse(Parser.java:562)
	at org.mozilla.javascript.Context.parse(Context.java:2470)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2401)
	at org.mozilla.javascript.Context.compileString(Context.java:1369)
	at org.mozilla.javascript.Context.compileString(Context.java:1357)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1135)
	at maestro.js.JsEngine.evaluateScript(JsEngine.kt:81)
	at maestro.js.JsEngine.evaluateScript$default(JsEngine.kt:58)
	at maestro.orchestra.Orchestra.defineVariablesCommand(Orchestra.kt:256)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:193)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:141)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)
	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:73)
	at maestro.cli.runner.TestSuiteInteractor.runFlow(TestSuiteInteractor.kt:141)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:72)
	at maestro.cli.runner.TestSuiteInteractor.runTestSuite(TestSuiteInteractor.kt:52)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:142)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:124)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:96)
	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:54)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:124)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:42)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:125)
```

**Comment by axelniklasson** [comment] 2023-05-03 15:30
Hi folks, thanks for reporting this. If you [upgrade to the most recent version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), are you still experiencing issues? If so, please share reproduction steps (Flows and app file) if you are able to and we will take a look.

**Comment by yanniks** [comment] 2023-05-04 12:44
For me, the problem is solved with the most recent version. Thank you!

**Comment by axelniklasson** [comment] 2023-05-16 08:13
Hey folks, I'm closing this one out. If you still experience issues regarding this, please open a new bug report.

**Closed by axelniklasson** 2023-05-16 08:13 UTC
Labels: bug, needs-information
