### ISSUE TITLE
Close keyboard clears field masks

### ISSUE THREAD

**Issue by julioexacta** [mobile-dev-inc/maestro#638] opened 2023-01-18 21:17 UTC
When I use the command to close my device's keyboard, it ended up clearing the masks of some fields that I had in my form, which I can't do manually, so I imagine it is something related to the command executed when closing the keyboard using the Maestro command.

**Comment by axelniklasson** [comment] 2023-05-03 14:28
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:28 UTC
