### ISSUE TITLE
[Android] Vertical scroll not working inside a webview rendered inside the activity

### ISSUE THREAD

**Issue by aakash1313** [mobile-dev-inc/maestro#277] opened 2022-10-13 16:24 UTC
We have a use case where we have to launch google custom tabs and perform a vertical scroll inside that , but it seems that is not scroll on it. 

Here's a screen record with a snippet of the script : 

```
- tapOn:
    text: "Sign in"
    optional: true    
- tapOn:
    text: "olmuitesting2@gmail.com"
    optional: true
- tapOn:
    text: .*Microsoft*.
    optional: true    
- scroll      
- tapOn:
    text: "Allow"
    rightOf: "Cancel"

```

![screenshot-1665678160818](https://user-images.githubusercontent.com/3194646/195653479-24fa68a7-25ef-40e9-93f1-279d9018a05e.png)

**Comment by aakash1313** [comment] 2022-10-13 17:22
I think the issue with this and potentially some other use case would be that maestro is not able to add the focus on the correct view . Is there a way to achieve that ?

**Comment by axelniklasson** [comment] 2023-05-03 13:43
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 13:43 UTC
