### ISSUE TITLE
Maestro bitbucket pipeline fails with Android

### ISSUE THREAD

**Issue by AlexGuiraoLopez** [mobile-dev-inc/maestro#1612] opened 2023-12-04 14:39 UTC
**Describe the bug**
I'm using Maestro with Bitbucket pipeline for the first time with an Android project. I set all the steps from documentation but when pipeline executes it seems to fail for some reason.
Installation was successful!  message appear and some instructions of how to use maestro but it doesn't execute the tests.

**To Reproduce**
Steps to reproduce:

1. Prepare the YAML file for bitbucket as in Maestro documentation:
pipelines:
    default:
      - step:
          name: Android Debug Application
          caches:       # caching speed up subsequent execution
            - gradle
          script:
            - ./gradlew assembleStgDebug
          artifacts:
            - app/build/outputs/**       # artifacts are files that are produced by a step
      - step:
          name: Maestro UI test
          script:
            - pipe: mobiledevinc/maestro-cloud-upload:1.2.0 # maestro UI testing.
              variables:
                MDEV_API_KEY: $MAESTRO_TOKEN
                MDEV_APP_FILE: app/build/outputs/apk/stg/debug/app-stg-debug.apk
3. Push to Bitbucket
4. The Flow fails at pipeline execution

**Expected behavior**
Run Maestro test and receive its response.

**Screenshots**
![yaml bitbucket pipeline](https://github.com/mobile-dev-inc/maestro/assets/73042607/ce7a4b88-1aed-4d1e-945e-0965cd57fdb3)![bitbucket response](https://github.com/mobile-dev-inc/maestro/assets/73042607/3a4f3011-c926-4d2d-9588-ff1f3479753b)

**Environment information (please complete the following information):**

- Maestro version mobiledevinc/maestro-cloud-upload:1.2.0
- Platform: Android 12
- Framework: Android
- Simulator
- Host Bitbucket pipeline

**Bugreport output:
[pipelineLog-{60b3e6c3-879c-4550-b829-57b8b758f199}.txt](https://github.com/mobile-dev-inc/maestro/files/13559147/pipelineLog-.60b3e6c3-879c-4550-b829-57b8b758f199.txt)

**Comment by axelniklasson** [comment] 2023-12-05 09:31
@AlexGuiraoLopez could you post the full output of the log from BitBucket please?

**Comment by AlexGuiraoLopez** [comment] 2023-12-05 11:00
> @AlexGuiraoLopez could you post the full output of the log from BitBucket please?

pipelineLog-{60b3e6c3-879c-4550-b829-57b8b758f199}.txt

**Comment by axelniklasson** [comment] 2023-12-07 09:03
Thanks. Looks like the upload pipe can't find your Flows. Is your workspace present in the root directory of your repo and called `.maestro`? Otherwise you need to set `MDEV_WORKSPACE` with the path to your workspace as outlined in the [docs](https://bitbucket.org/bitbucket/product/features/pipelines/integrations?search=maestro&p=mobiledevinc/maestro-cloud-upload).

**Comment by AlexGuiraoLopez** [comment] 2023-12-11 08:32
Yes, my .maestro folder is located in android project root directory and tests inside:
<img width="273" alt="Captura de pantalla 2023-12-11 a las 9 32 18" src="https://github.com/mobile-dev-inc/maestro/assets/73042607/c7eab681-91f9-41f4-a886-03dcb6b9cced">

**Comment by axelniklasson** [comment] 2023-12-11 10:38
>  android project root directory
Is this the same as the root directory of your repository or do you have a monorepo with multiple projects in the same repository? If so you need to set `MDEV_WORKSPACE` to the `ANDROID_PROJECT/.maestro`

**Comment by AlexGuiraoLopez** [comment] 2023-12-11 13:38
Is the root of the bitbucket repository too.

**Comment by axelniklasson** [comment] 2023-12-11 13:59
Got it, thanks. Passing this to @ArthurSav who has more context on our Bitbucket pipelines -- Arthur, can you please help out here?

**Comment by SimenRom** [comment] 2023-12-12 15:25
Got the same issue now where its executed with `maestro cloud`-command from the CI. Worked perfectly fine for 1 or 2 weeks ago.

**Comment by AlexGuiraoLopez** [comment] 2024-01-15 11:02
Any news about this issue? @axelniklasson

**Comment by ArthurSav** [comment] 2024-01-18 10:58
@AlexGuiraoLopez Can you set the workspace path explicitly? You can do this like so:

```yaml
script:
  - pipe: mobiledevinc/maestro-cloud-upload:1.2.0
    variables:
      MDEV_API_KEY: "<string>"
      MDEV_APP_FILE: "<string>"
      MDEV_WORKSPACE: .maestro (or path to wherever the workspace folder is located)
```

If that doesn't work, please post the full pipe output again.

**Comment by AlexGuiraoLopez** [comment] 2024-06-12 13:04
I've tried to specify workspace and now I get different error:

```
Welcome to Maestro!
+ export PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.maestro/bin
+ [ ! -z  ]
+ maestro cloud --apiKey $MAESTRO_TOKEN --branch composing/ui_migration_to_compose --repoName iatiapp_android --name 279 app/build/outputs/apk/stg/debug/app-stg-debug.apk .maestro
Evaluating workspace...
Uploading Flow(s)...
....................
Upload request failed (400): Workspace doesn't have any flow
```

**Comment by bartekpacia** [comment] 2024-08-24 15:12
Hey, revisiting this to say this doesn't look like a Maestro-related problem, but BitBucket Pipelines specific.

Because of that, closing. Try creating [a minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and asking BitBucket support or StackOverflow.

**Closed by bartekpacia** 2024-08-24 15:12 UTC
Labels: bug, needs more info
