### ISSUE TITLE
Scroll vertically not working on SDK30 emulator

### ISSUE THREAD

**Issue by poojaustad** [mobile-dev-inc/maestro#344] opened 2022-11-01 12:00 UTC
OBSERVATION:
We are automating our Ustad mobile app using Maestro. On one test flow, we have to disable -the publicly accessible switch. In order to view this switch we need to scroll vertically. Scroll functionality shows as completed on the log but it's not actually scrolling the SDK 30 emulator. It seems to work on other emulator versions.

Steps to reproduce issue :
1) Set emulator with below specifications
Emulator specification:
$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
$ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n avd30 -k "system-images;android-30;google_apis;x86_64"

2) click on this link [LINK](https://drive.google.com/drive/folders/11-9LuFCBFem6OFsWOuiv-vGpWHVGQ2Oc?usp=share_link ) and download folder named - scroll_issue

3) run command - ./test-ui/android-maestro/run-maestro-tests.sh --serial emulator-5554 --apk /home/ustadmobile/Downloads/scroll_issue/Primary394.apk --tests test-ui/android-maestro/tests/001_007_admin_can_make_content_not_available_for_public/runtest.sh    

Note-
1) This issue was not reproduced on other emulator versions.
2) Using swipe: start: 100,400  end: 100,100 works on the SDK 30 emulator (workaround)

[Screencast002.webm](https://user-images.githubusercontent.com/78338755/199222360-b78b22dc-80d1-4a10-a6cb-05ee8aaf3247.webm)

Thanks.

**Comment by Leland-Takamine** [comment] 2023-05-03 13:39
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on the scroll command since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by Leland-Takamine** 2023-05-03 13:39 UTC
