### ISSUE TITLE
Whether maestro supports validation in Real iOS device?

### ISSUE THREAD

**Issue by Arulsundarmts** [mobile-dev-inc/maestro#1429] opened 2023-09-07 17:08 UTC
Whether maestro supports validation in Real iOS device?

or its just limited to Simulator for now ?

**Comment by amanjeetsingh150** [comment] 2023-09-11 07:47
What do you mean by validation here?

**Comment by bartekpacia** [comment] 2024-07-12 23:23
Closing as duplicate of #686

**Closed by bartekpacia** 2024-07-12 23:23 UTC
