### ISSUE TITLE
[Feature Request] Ability to query Maestro runtime information (e.g current test)

### ISSUE THREAD

**Issue by btrautmann** [mobile-dev-inc/maestro#1395] opened 2023-08-28 20:31 UTC
**Is your feature request related to a problem? Please describe.**

We are investigating ways through which we can record and play back network interactions during a Maestro test. One requirement that we've run up against is the ability to know _which_ test is running so that we can match request/response pairs to the correct test. 

We're aware that you can check [whether your app is running in a Maestro environment](https://maestro.mobile.dev/advanced/detect-maestro-in-your-app), but we'd also like to be able to query what test is running.

**Describe the solution you'd like**

We imagine being able to hit a "Maestro API" on a loopback address, something like:

```dart
// some_interceptor.dart
Future<void> onRequest(req, handler) async {
  if (isRunningInMaestro()) {
    final testName = await _maestroApi.fetchTestName();
    final session = await _requestDataStore.fetch(testName);
    final response = session[req];
    if (response != null) {
      handler.resolve(response);
    } else {
      handler.next(request);
    }
  } else {
    handler.next(request)
} 
```

**Describe alternatives you've considered**

Alternatives are hard here (though we're very open to them!): Since Maestro is running in a black-box, and we don't want to re-build our app between test runs, there's no way to inject this information into the application other than at runtime via Maestro (as far as we can tell...).

**Comment by bartekpacia** [comment] 2024-07-12 23:45
Hey, thank you for this issue. This sounds like a duplicate of #1616 to me (yes I know it was created later, but I triaged it in a reverse order, sorry bout that!). Going to close it, but please feel free to comment if I'm wrong!

**Closed by bartekpacia** 2024-07-12 23:45 UTC
Labels: enhancement
