### ISSUE TITLE
Error on swipe

### ISSUE THREAD

**Issue by idrakimuhamad** [mobile-dev-inc/maestro#625] opened 2023-01-17 10:15 UTC
I received an error below when trying to do `swipe` action on my  React Native app.

```yaml
- assertVisible:
    id: "dealsCarousel"
- swipe:
    direction: LEFT
    from:
      id: "dealsCarousel"
```

`dealsCarousel` is a `FlatList`

```
maestro -v
1.19.0
```

<details>
<summary>Stack error</summary>
java.lang.IllegalStateException: Device width not available
	at maestro.drivers.IOSDriver.swipe(IOSDriver.kt:404)
	at maestro.Maestro.swipe(Maestro.kt:124)
	at maestro.orchestra.Orchestra.swipeCommand(Orchestra.kt:764)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:172)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:137)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:91)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:88)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:87)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:23)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:87)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:75)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
</details>

If I use a hardcoded coordinates, below error thrown

```
- swipe:
    start: 166, 177
    end: 300, 177
```

<details>
<summary>Another trace</summary>
java.lang.IllegalStateException: Screen width not available
	at maestro.drivers.IOSDriver.validate(IOSDriver.kt:303)
	at maestro.drivers.IOSDriver.swipe(IOSDriver.kt:326)
	at maestro.Maestro.swipe(Maestro.kt:116)
	at maestro.orchestra.Orchestra.swipeCommand(Orchestra.kt:766)
	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:172)
	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:137)
	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:91)
	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:88)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2$1.invoke(TestRunner.kt:87)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.access$runCatching(TestRunner.kt:23)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:87)
	at maestro.cli.runner.TestRunner$runContinuous$watchFiles$1$2.invoke(TestRunner.kt:75)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
</summary>

**Comment by artem888** [comment] 2023-01-17 12:25
hey @idrakimuhamad ! thanks for reporting, the issue is fixed. it's going to be released with the new upcoming maestro cli version 1.19.1

https://github.com/mobile-dev-inc/maestro/pull/617

**Closed by artem888** 2023-01-17 12:25 UTC

**Comment by idrakimuhamad** [comment] 2023-01-17 12:55
Sweet. Thanks for the good work!
