### ISSUE TITLE
"Unable to obtain active app id" error on maestro commands for iOS

### ISSUE THREAD

**Issue by edgarfroes** [mobile-dev-inc/maestro#646] opened 2023-01-19 20:16 UTC
I get the error below when running commands on an iOS simulator on the latest maestro version (`1.19.5`):

Commands that I've tested so far and that are failing: `test`, `studio`, and `hierarchy`.

<details><summary>Click to see the complete error log</summary>
<p>

``` bash
java.lang.IllegalStateException: Unable to obtain active app id                      
        at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:48)       
        at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:32)                
        at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:175)             
        at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:344)           
        at maestro.Maestro$findElementWithTimeout$1.invoke(Maestro.kt:343)           
        at maestro.utils.MaestroTimer.withTimeout(MaestroTimer.kt:16)                
        at maestro.Maestro.findElementWithTimeout(Maestro.kt:343)                    
        at maestro.orchestra.Orchestra.findElement(Orchestra.kt:646)                 
        at maestro.orchestra.Orchestra.findElement$default(Orchestra.kt:628)         
        at maestro.orchestra.Orchestra.tapOnElement(Orchestra.kt:558)                
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:159)              
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:443)                  
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:358)              
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:185)              
        at maestro.orchestra.Orchestra.runSubFlow(Orchestra.kt:443)                  
        at maestro.orchestra.Orchestra.runFlowCommand(Orchestra.kt:358)              
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:185)              
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:137)             
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:91)                      
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36) 
	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)
	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)
	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:139)
	at maestro.cli.command.TestCommand$call$1.invoke(TestCommand.kt:100)
	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:92)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:100)
	at maestro.cli.command.TestCommand.call(TestCommand.kt:39)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:122)
```

</p>
</details>

## A few key points:
1 - When running `xcrun simctl list devices booted` I get only one device running, which is my emulator.
2 - I thought that it was a problem where I had `Connect via network` enabled on my physical device on Xcode's `Window > Devices and Simulators > Devices > Select my physical device`, so I disabled it and the error still persisted. Tried disabling the option `Show as run destination` as well.
3 - Tried to set the device id with `maestro --device=[DEVICE_ID_HERE] test clear_safari_cache.yaml`.
4 - Tried with different and newly created iOS simulators.
5 - Tried restarting the mac.
6 - The same error is happening when I try to run maestro studio.
7 - The same error is also occurring on maestro version `1.19.2`, which leads me to ask: is there a problem with external dependencies getting upgraded and breaking maestro?
8 - Upon locally running the command `xcrun simctl listapps booted` in [this function](https://github.com/mobile-dev-inc/maestro/blob/f1b331a3fb5bf2fba28077d1978cf0de7d3d361a/maestro-xcuitest-driver/src/main/kotlin/util/XCRunnerSimctl.kt#L37), the app that I'm using as the `appId` property of the `yaml` test file is being listed properly.

## Steps to reproduce:
1 - Boot an iOS Simulator
2 - Create the file below and name it `clear_safari_cache.yaml`
3 - Run `maestro test clear_safari_cache.yaml`

```yaml
appId: com.apple.Preferences
---
- launchApp
- tapOn: "Safari"
- swipe:
    direction: UP
    duration: 300
- tapOn: "Clear History and Website Data"
- tapOn: "Clear History and Data"
- tapOn: "Close Tabs"
- stopApp
```

**Comment by edgarfroes** [comment] 2023-01-19 20:36
Update: the same error is happening when I try to run `maestro studio`.


<details><summary>Click to see the complete error log</summary>
<p>


``` bash
Navigate to http://localhost:9999 in your browser to open Maestro Studio. Ctrl-C to exit.
java.lang.IllegalStateException: Unable to obtain active app id
	at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:48)
	at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:32)
	at maestro.drivers.IOSDriver.contentDescriptor(IOSDriver.kt:175)
	at maestro.ViewHierarchy$Companion.from-c1iYVAs(ViewHierarchy.kt:28)
	at maestro.Maestro.viewHierarchy-prqvCes(Maestro.kt:320)
	at maestro.studio.DeviceScreenService$routes$1.invokeSuspend(DeviceScreenService.kt:41)
	at maestro.studio.DeviceScreenService$routes$1.invoke(DeviceScreenService.kt)
	at maestro.studio.DeviceScreenService$routes$1.invoke(DeviceScreenService.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.routing.Routing.executeResult(Routing.kt:174)
	at io.ktor.server.routing.Routing.interceptor(Routing.kt:49)
	at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:124)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:123)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:43)
	at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
	at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:42)
	at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
	at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:370)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:288)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

</p>
</details>

**Comment by edgarfroes** [comment] 2023-01-19 20:39
**Update**: The same error is also occurring on `1.19.2`, which leads me to think that this is a problem with external dependencies getting upgraded and breaking maestro.

**Comment by edgarfroes** [comment] 2023-01-19 21:09
**Update**: I've added key points 6, 7, and 8 to the main post.

**Comment by amanjeetsingh150** [comment] 2023-01-20 06:13
Hey, @edgarfroes can you dump bug report with `maestro bugreport` and submit all the reports in a zip.

**Comment by edgarfroes** [comment] 2023-01-20 15:30
@amanjeetsingh150 Done.

The first one is when running `maestro test` and the second one is when running `maestro studio`.

[2023-01-20_122642.zip](https://github.com/mobile-dev-inc/maestro/files/10467640/2023-01-20_122642.zip)
[2023-01-20_122851.zip](https://github.com/mobile-dev-inc/maestro/files/10467641/2023-01-20_122851.zip)

**Comment by marciliojrs** [comment] 2023-01-23 14:11
Having the same issue when trying to run the `maestro studio` 

If that helps @amanjeetsingh150, there's another dump. 
[2023-01-23_110804.zip](https://github.com/mobile-dev-inc/maestro/files/10480448/2023-01-23_110804.zip)

**Comment by amanjeetsingh150** [comment] 2023-01-24 18:17
Hey @marciliojrs @edgarfroes we are root causing this. Can confirm me these things:
* Were you using multiple sessions of maestro when before or while you face this errors
* Can you delete this directory with command: `~/.maestro/sessions` and try again to check if these commands work?

**Comment by marciliojrs** [comment] 2023-01-24 19:17
Hi @amanjeetsingh150, In my case, I wasn't using multiple sessions and also tried after deleting the `sessions` folder as you explained and nothing. Tested in the latest CLI version (1.20.o) and the error persists. 

Short video reproducing the issue:

https://user-images.githubusercontent.com/732738/214386731-2c1604f0-77a4-4e05-937d-82b0912a355f.mp4

The maestro studio issue:

https://user-images.githubusercontent.com/732738/214387124-a942c4f9-9271-41c3-bb1f-f8f279d7031d.mp4

logs:
[2023-01-24_161448.zip](https://github.com/mobile-dev-inc/maestro/files/10493231/2023-01-24_161448.zip)
[2023-01-24_161508.zip](https://github.com/mobile-dev-inc/maestro/files/10493227/2023-01-24_161508.zip)

**Comment by amanjeetsingh150** [comment] 2023-01-24 19:59
Hey @marciliojrs there would be a `xctest_runner_logs` directory as well. Can you submit the the zip of the directory as well that contains logs of the new driver

**Comment by marciliojrs** [comment] 2023-01-24 20:05
[maestro logs.zip](https://github.com/mobile-dev-inc/maestro/files/10493537/maestro.logs.zip)

sorry, cleaned everything here. 
sending another set of logs for `maestro studio`

**Comment by amanjeetsingh150** [comment] 2023-01-24 20:15
Ummm, @marciliojrs is this iOS version 13.x.x?

**Comment by amanjeetsingh150** [comment] 2023-01-24 20:47
Hey @marciliojrs thanks 🙌 can you send multiple reports by running maestro studio and test command both wanted to see if there is any pattern

**Comment by marciliojrs** [comment] 2023-01-24 23:23
[logs.zip](https://github.com/mobile-dev-inc/maestro/files/10494738/logs.zip)

Logs for maestro studio. Now I'm trying to run the test .. it's starting the flow but the `tapOn` isn't finding the item. 🤔

**Comment by marciliojrs** [comment] 2023-01-24 23:31
Sorry @amanjeetsingh150 , I've downgraded maestro here to test if it helps and sent you logs from an old version. Sending the correct ones for 1.20.0.

[logs1.20.0-studio.zip](https://github.com/mobile-dev-inc/maestro/files/10494775/logs1.20.0-studio.zip)
[logs1.20.0-test.zip](https://github.com/mobile-dev-inc/maestro/files/10494773/logs1.20.0-test.zip)

**Comment by amanjeetsingh150** [comment] 2023-01-25 18:40
Hey @marciliojrs @edgarfroes  thanks for the logs and helping in debugging 🙌  can you folks reproduce this issue in latest: 1.21.0 and provide the same logs? That has some logging improvements that can help in the further investigation, I will keep you updated on the investigation and release on this one.

**Comment by marciliojrs** [comment] 2023-01-26 11:38
Hi @amanjeetsingh150 seems everything working now. I've changed my environment here to Xcode 14.2 also, don't know if that helped. 🚀

**Comment by efstathiosntonas** [comment] 2023-01-26 14:07
same here using `1.21.1`

[2023-01-26_160527.zip](https://github.com/mobile-dev-inc/maestro/files/10510000/2023-01-26_160527.zip)
[2023-01-26_160537.zip](https://github.com/mobile-dev-inc/maestro/files/10510001/2023-01-26_160537.zip)

**Comment by amanjeetsingh150** [comment] 2023-01-26 18:20
Hey @efstathiosntonas, curious if you have a localhost running on 9080 port already while working on maestro test by any chance?

**Comment by amanjeetsingh150** [comment] 2023-01-26 18:21
Hey @marciliojrs, were you working with localhost running on 9080 port when you got that error?

**Comment by amanjeetsingh150** [comment] 2023-01-27 06:02
Hey @edgarfroes @marciliojrs @efstathiosntonas I was able to reproduce this locally, can you check if you folks had a localhost running already on port 9080? If yes can you stop that process and try running maestro again? If this resolves your issue let me know we'll get a fix prepared for this one.

**Comment by efstathiosntonas** [comment] 2023-01-27 06:04
@amanjeetsingh150 sure, will check asap

**Comment by efstathiosntonas** [comment] 2023-01-27 06:35
@amanjeetsingh150 you were right, docker is using that port: 
![Screenshot 2023-01-27 at 08 31 30](https://user-images.githubusercontent.com/717975/215023682-343aadf8-3d06-41bd-86a8-d1d690bb254c.png)


killing docker allowed maestro to work.

**Comment by amanjeetsingh150** [comment] 2023-01-27 06:49
Hey @efstathiosntonas thanks for the info does it continuously fail with this exception? Can you try with new terminal session?

**Comment by efstathiosntonas** [comment] 2023-01-27 06:53
I've killed running session, closed terminal, reopened, `maestro studio` -> same error as above. Tried 2-3 times

**Comment by amanjeetsingh150** [comment] 2023-01-27 06:53
Is maestro studio failing or even maestro tests?

**Comment by efstathiosntonas** [comment] 2023-01-27 06:54
it works fine, I can run tests on the browser

**Comment by amanjeetsingh150** [comment] 2023-01-27 06:56
Ohhh ok, so maestro studio is completely unusable for you. Can you check if the process with port 9999 is also killed? That is the studio's port I believe.

**Comment by efstathiosntonas** [comment] 2023-01-27 06:57
No, maestro studio works as expected, I can run tests on the browser, tap elements on app etc and then playback the tests.

**Comment by amanjeetsingh150** [comment] 2023-01-27 07:00
Ahh got it so both maestro studio and maestro test commands are successful. Its just that this exception (ChannelWriteException) is like a non-fatal?

**Comment by efstathiosntonas** [comment] 2023-01-27 07:01
exactly!

**Comment by amanjeetsingh150** [comment] 2023-01-27 07:04
Ahh got it thanks for pairing on this, I'll note this behavior and see if we can fix that nonfatal. @edgarfroes let me know if this works for you as well.

**Comment by efstathiosntonas** [comment] 2023-01-27 07:07
@amanjeetsingh150 you're welcome, happy to help. Thank you for this amazing product. We're awaiting for real iOS device 🥳

**Comment by efstathiosntonas** [comment] 2023-01-27 07:10
@amanjeetsingh150 don't know if it's related with the non-fatal error but I'm using Firefox Developer Edition, not Chrome.

**Comment by edgarfroes** [comment] 2023-01-27 17:42
@amanjeetsingh150 I had the Logitech Hub service, the one that manages my Logitech Mouse, running on port 9080. Killing the service made it work locally. I'm gonna trigger a new build in the CI (Codemagic) with the latest version and see what happens.

**Comment by edgarfroes** [comment] 2023-01-27 18:27
What if maestro tries to find an available port instead of using 9080 only?

**Comment by amanjeetsingh150** [comment] 2023-01-30 10:07
> I'm gonna trigger a new build in the CI (Codemagic) with the latest Maestro version and see what happens.

Awesome do check on CI if 9080 is free.


> What if maestro gets to find an available port instead of using 9080 only?

We will be addressing this in subsequent versions

**Comment by amanjeetsingh150** [comment] 2023-01-30 10:08
> @amanjeetsingh150 you're welcome, happy to help. Thank you for this amazing product. We're awaiting for real iOS device support 🥳

Hey @efstathiosntonas thanks 🙌  Its going to be soon there definitely. We are slowly migrating away from idb which will enable real device support.

>

**Comment by georges** [comment] 2023-02-02 19:57
Ran into same issue today. Logitech GHub seems to be listening to port 9080 as well...

**Comment by amanjeetsingh150** [comment] 2023-02-10 18:19
This should be fixed now folks, feel free to download the new version of maestro. Feel free to reach out in case you find any issues.

Maestro version: 1.22.1

**Closed by amanjeetsingh150** 2023-02-10 18:19 UTC
