### ISSUE TITLE
high memory using  

### ISSUE THREAD

**Issue by itsrahulsah** [mobile-dev-inc/maestro#994] opened 2023-04-14 12:13 UTC
I tried to run flow through maestro studio after it occupies 11 GB Memory have u any solution

**Comment by felipevolpone** [comment] 2023-04-24 14:43
@itsrahulsah can you provide more details about this? It would be useful to have a screenshot of the "Activity Monitor" if you use Mac OS or the equivalent for Windows or Linux (`top` command is enough). Also, it would be useful to know if you were running simulators, which flow you tried, etc.

**Comment by itsrahulsah** [comment] 2023-04-26 12:03
hi @felipevolpone  I'm using Ubuntu 20.04.4 LTS and Maestro version 1.26.1

After running maestro studio 
![Screenshot from 2023-04-26 17-17-30](https://user-images.githubusercontent.com/84001019/234568696-45cdc8b4-72c7-4715-a2ed-3ccbb1bd2a42.png)



before executing 1 to 2 commands 

![Screenshot from 2023-04-26 17-25-50](https://user-images.githubusercontent.com/84001019/234568955-edaf45d1-3789-4674-92d4-63da75eab5fd.png)

**Comment by felipevolpone** [comment] 2023-04-26 12:15
I'm not able to reproduce this issue and this is more likely related to the emulator rather than to Maestro Studio itself. Since there isn't much to do here right now, I'm closing this issue.

**Closed by felipevolpone** 2023-04-26 12:15 UTC
Labels: wontfix

**Comment by itsrahulsah** [comment] 2023-05-01 06:33
Hi bro,
I'm frustrated from your regular call so please stop this other wise , I
will take legal action against your company

**Comment by Leland-Takamine** [comment] 2023-05-02 15:23
Hey @itsrahulsah I'm not sure whether your reply was to the wrong email thread (this is the github issue thread you opened on the Maestro open source repo), but just in case: Our team does not make calls to authors of Maestro GitHub issues

**Comment by Leland-Takamine** [comment] 2023-05-02 17:28
No worries at all @itsrahulsah !
