### ISSUE TITLE
[Maestro 1.21.0] Maestro studio does not render correctly on safari

### ISSUE THREAD

**Issue by BrentMifsud** [mobile-dev-inc/maestro#678] opened 2023-01-25 19:29 UTC
The ui overlaps and is cut off:

![image](https://user-images.githubusercontent.com/18543934/214667759-7d854a41-0007-46eb-a10c-59606d5fb895.png)

**Comment by Leland-Takamine** [comment] 2023-01-25 19:29
We'll take a look thanks for reporting!

**Comment by axelniklasson** [comment] 2023-05-03 14:46
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro Studio since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:46 UTC
Labels: bug
