### ISSUE TITLE
index for repeated elements is unordered

### ISSUE THREAD

**Issue by amangupta-sharechat** [mobile-dev-inc/maestro#699] opened 2023-01-27 14:36 UTC
Environment - iOS

I have a UITableView with reused cells, everytime I relaunch the app and try to check the index using the hierarchy given by `maestro studio` tool, I get different indexes for the elements.
This makes it impossible to tap on correct item correctly.
Can we have something which assigns indexes based on the order in which they are loaded?

**Comment by dmitry-zaitsev** [comment] 2023-01-30 13:00
cc @Leland-Takamine

**Comment by axelniklasson** [comment] 2023-05-03 14:50
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on iOS support on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:50 UTC
