### ISSUE TITLE
[Feature Request] Can we have print statement in flow yaml 

### ISSUE THREAD

**Issue by findms** [mobile-dev-inc/maestro#1745] opened 2024-05-16 14:05 UTC
**Is your feature request related to a problem? Please describe.**
The problem is that we can not put logs after steps if it did passed or failed on console while running through tests folder where multiple flow files exist.
For example we use :
`console.log("XYZ step passed")`

**Describe the solution you'd like**
Something similar to console.log which accept string and print as it is.

**Comment by Fishbowler** [comment] 2024-05-17 14:11
I was hunting around for another hobby contribution, but I'm not sure I fully understand this. 

> we can not put logs after steps if it did passed or failed on console 

Are you talking about being able to log something after the flow has already failed?

**Comment by rasyid7** [comment] 2024-05-20 11:11
you can use `evalScript`

`- evalScript: ${console.log('Hello Word')}`

it's stated here https://maestro.mobile.dev/api-reference/commands/runscript#console-logging

**Comment by findms** [comment] 2024-05-20 21:44
@rasyid7 this is being executed as javascript..not sure if we can simply print something in yaml. While running tests via folder this print via `evalScript` is not shown on console. It only shows the element due to which test fail. no print statement before that because this is a action for maestro to execute javascript.

To add more details
Lets say there are 10 lines of action in yaml and I am running tests via flows folder(where it contains all the test flows)
 After 5th I have added evalScript to print that line 5th executed. If it failed on line 7th action due to any locator etc issue - console will not show the print on 5th it will show the fail on 7th with locator.

**Comment by bartekpacia** [comment] 2024-07-27 00:04
Hey, thanks everyone for chiming in!

I just found an issue that's basically a duplicate of this one – https://github.com/mobile-dev-inc/maestro/issues/517, and it's older and has more likes. So I'm going to close this one. Please move discussion to #517.

Thanks for understanding.

**Closed by bartekpacia** 2024-07-27 00:04 UTC
Labels: enhancement
