### ISSUE TITLE
how to : onSubmitEditing

### ISSUE THREAD

**Issue by kadirguloglu** [mobile-dev-inc/maestro#1143] opened 2023-06-09 16:04 UTC
I want to run a test on the onSubmitEditing instant. how can i trigger this event

**Comment by sevketaydogdu** [comment] 2023-06-09 16:06
realy needed

**Comment by amanjeetsingh150** [comment] 2023-06-12 03:59
Hey, @kadirguloglu can you explain in detail about the feature request:


**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by sevketaydogdu** [comment] 2023-06-12 07:57
Hey, @amanjeetsingh150
We want to run test when keyboard opened.
How to press returnKey on phones keyboard like "Go", "Submit" etc.

![image](https://github.com/mobile-dev-inc/maestro/assets/44119231/a82c88cc-ef5c-4615-b13a-896d7b5f5db6)

**Comment by felipevolpone** [comment] 2023-09-04 11:56
This is out of the scope of maestro and our ideas for the framework. Closing this as won't fix

**Closed by felipevolpone** 2023-09-04 11:56 UTC
