### ISSUE TITLE
[Feature Request] setLocation to accept external env variables

### ISSUE THREAD

**Issue by elcaptain** [mobile-dev-inc/maestro#1536] opened 2023-10-18 13:41 UTC
**Is your feature request related to a problem? Please describe.**
Right now `setLocation` does not accept external env variables.

file.yaml:
```
appId: xxx
---
- launchApp
- waitForAnimationToEnd
- setLocation:
    latitude: ${lat}
    longitude: ${long}
``` 
run:
`maestro test -e lat=52.390568 long=-2.587910 file.yaml`

error:
`Cannot deserialize value of type `double` from String "${lat}": not a valid `double` value (as String to convert)`

**Describe the solution you'd like**
I'd like `setLocation` to accept external env variables.

**Describe alternatives you've considered**
I've tried wrapping the number in quotes but it did nothing: `maestro test -e lat='52.390568' long='-2.587910' file.yaml`

**Comment by zereight** [comment] 2023-11-01 07:51
me too

**Comment by volkanakbayir** [comment] 2024-03-16 10:19
same here

**Comment by dgreasi** [comment] 2024-05-01 08:41
Same here

**Comment by ubuntudroid** [comment] 2024-05-02 16:13
I have the feeling this is the case for all built-in parameters which aren't of type `String`. And it doesn't just affect external env variables, but env variables in general.

Doing something like

```yaml
launchApp:
  clearState: ${clearState}
```

results in a similar

```
Cannot deserialize value of type `java.lang.Boolean` from String "${ clearState }": only "true" or "false" recognized
```

**Comment by Arron-Gill** [comment] 2024-05-03 17:37
Same here

**Comment by bartekpacia** [comment] 2024-07-11 01:20
Thank y'all for creating the issue and chiming in.

There's already a PR for that, should land soon: #1769.

I'm going to close it as duplicate of https://github.com/mobile-dev-inc/maestro/issues/1765

**Closed by bartekpacia** 2024-07-11 01:20 UTC
Labels: enhancement
