### ISSUE TITLE
Maestro not picking up id's for components other than buttons and text

### ISSUE THREAD

**Issue by antoniofranciscoandrade** [mobile-dev-inc/maestro#318] opened 2022-10-25 22:54 UTC
Building a react-native project and only buttons and text components are shown when calling `maestro hierarchy`. Other components have id's assigned too and Maestro isn't picking it up. Have tried using `accessibilityLabel`, `nativeID` and `data-testid` but none work.

To reproduce, run `maestro hierarchy` on a starter project with the code below and check that it only prints the text and button id's on the hierarchy.

```
import {StatusBar, View, Text, Button, Image} from 'react-native';
import Svg, {Path} from 'react-native-svg';

const App = () => (
  <View
    testID="view-id"
    data-testid="view-id"
    nativeID="view-id"
    accessibilityLabel="view-id">
    <Text testID="text-id">hello world</Text>
    <Button title="button" testID="button-id"/>
    <Image
      source={{
        uri: 'https://res.cloudinary.com/demo/image/upload/v1312461204/sample.jpg',
      }}
      testID="image-id"
      data-testid="image-id"
      nativeID="image-id"
      accessibilityLabel="image-id"
    />
    <Svg
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      testID="svg-id"
      data-testid="svg-id"
      nativeID="svg-id"
      accessibilityLabel="svg-id">
      <Path
        d="M9.92902 11.9997L13.75 8.17866C14.164 7.76466 14.164 7.09266 13.75 6.67866C13.336 6.26466 12.664 6.26466 12.25 6.67866L7.63602 11.2927C7.24502 11.6837 7.24502 12.3167 7.63602 12.7067L12.25 17.3207C12.664 17.7347 13.336 17.7347 13.75 17.3207C14.164 16.9067 14.164 16.2347 13.75 15.8207L9.92902 11.9997Z"
        fill="black"
      />
    </Svg>
  </View>
);

export default App
```

**Comment by maudjossier** [comment] 2022-10-27 13:31
I'm having the same issue

**Comment by axelniklasson** [comment] 2023-05-03 13:51
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro with regards to React Native ([docs here](https://maestro.mobile.dev/platform-support/react-native)) since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 13:51 UTC

**Comment by philiplindberg** [comment] 2023-06-27 11:58
I can confirm that this is still happening with Maestro v1.29.0 and React Native v0.71.8.
