### ISSUE TITLE
Android API 24 - Device not found

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#268] opened 2022-10-11 16:27 UTC
Error I get when running `maestro --platform android hierarchy` on Pixel 2 arm64 emulator API 24:

```
java.io.IOException: Failed to install apk /var/folders/nh/kq5bbcj16vs4zj4q6ylkzylh0000gn/T/maestro-app4520222182655224887.apk: Broken pipe (Write failed)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:386)
	at maestro.drivers.AndroidDriver.installMaestroApks(AndroidDriver.kt:366)
	at maestro.drivers.AndroidDriver.open(AndroidDriver.kt:73)
	at maestro.Maestro$Companion.android(Maestro.kt:394)
	at maestro.Maestro$Companion.android$default(Maestro.kt:392)
	at maestro.cli.util.MaestroFactory.createAndroid(MaestroFactory.kt:56)
	at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:36)
	at maestro.cli.command.PrintHierarchyCommand.run(PrintHierarchyCommand.kt:36)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:88)
Caused by: java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at okio.OutputStreamSink.write(JvmOkio.kt:57)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
	at okio.RealBufferedSink.write(RealBufferedSink.kt:185)
	at dadb.AdbWriter.write(AdbWriter.kt:90)
	at dadb.AdbWriter.writeWrite(AdbWriter.kt:56)
	at dadb.AdbStreamImpl$sink$1.flush(AdbStream.kt:103)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:269)
	at dadb.AdbSyncStream.writePacket(AdbSync.kt:103)
	at dadb.AdbSyncStream.send(AdbSync.kt:60)
	at dadb.Dadb$DefaultImpls.push(Dadb.kt:54)
	at dadb.DadbImpl.push(DadbImpl.kt:23)
	at dadb.Dadb$DefaultImpls.push(Dadb.kt:48)
	at dadb.DadbImpl.push(DadbImpl.kt:23)
	at dadb.Dadb$DefaultImpls.push$default(Dadb.kt:47)
	at dadb.Dadb$DefaultImpls.install(Dadb.kt:90)
	at dadb.DadbImpl.install(DadbImpl.kt:23)
	at maestro.drivers.AndroidDriver.install(AndroidDriver.kt:384)
	... 15 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
		at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
		at okio.OutputStreamSink.write(JvmOkio.kt:57)
		at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
		at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
		at okio.RealBufferedSink.writeIntLe(RealBufferedSink.kt:230)
		at dadb.AdbWriter.write(AdbWriter.kt:78)
		at dadb.AdbWriter.writeWrite(AdbWriter.kt:56)
		at dadb.AdbStreamImpl$sink$1.flush(AdbStream.kt:103)
		at okio.RealBufferedSink.flush(RealBufferedSink.kt:269)
		at dadb.AdbSyncStream.writePacket(AdbSync.kt:103)
		at dadb.AdbSyncStream.close(AdbSync.kt:114)
		at kotlin.jdk7.AutoCloseableKt.closeFinally(AutoCloseable.kt:64)
		at dadb.Dadb$DefaultImpls.push(Dadb.kt:53)
		... 22 more
```

**Comment by axelniklasson** [comment] 2023-05-03 13:43
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 13:43 UTC
Labels: bug, android
