### ISSUE TITLE
[iOS] scrollUntilVisible or scroll throw an Error

### ISSUE THREAD

**Issue by ludwig-pro** [mobile-dev-inc/maestro#791] opened 2023-02-13 18:55 UTC
I'm trying to use scrollUntilVisible on iOS with a react-native app but there is an error, my scrolling view needs two "scrolls" to reach the bottom but the test crashes after the first one and a freeze period.

the test is particularly flaky when I need to scroll...

nb: I ran my app in debug

```
// I tried
- scrollUntilVisible:
    element:
      text: 'Log out'
    direction: 'DOWN'
    speed: 60
    
 OR
 
 - scroll
 - scroll
```

## My view
<img src="https://user-images.githubusercontent.com/62896243/218548004-e28db9bd-5088-42a1-b662-3448d3b4f228.png" width="375" />

## Error
```
com.github.michaelbull.result.UnwrapException: kotlin.Unit java.lang.IllegalStateException: network interceptor xcuitest.XCTestDriverClient$okHttpClient$2$$Lambda$141/0x000000080056a840@1e9469b8 must call proceed() exactly once                                                                                        
        at maestro.drivers.IOSDriver.directionalSwipe(IOSDriver.kt:414)                                                                                     
        at maestro.drivers.IOSDriver.swipe(IOSDriver.kt:377)                                                                                                
        at maestro.Maestro.swipeFromCenter(Maestro.kt:164)                                                                                                  
        at maestro.orchestra.Orchestra.scrollUntilVisible(Orchestra.kt:296)                                                                                 
        at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:172)                                                                                     
        at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:138)                                                                                    
        at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:92)                                                                                             
        at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:120)                                                                 
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:36)                                                                        
        at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:32)                                                                        
        at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:123)                                                                                     
        at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:32)                                                                                        
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:87)                                                                             
        at maestro.cli.command.RecordCommand$call$1.invoke(RecordCommand.kt:72)                                                                             
        at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:98)                                                                
        at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:53)                                                        
        at maestro.cli.command.RecordCommand.call(RecordCommand.kt:72)                                                                                      
	at maestro.cli.command.RecordCommand.call(RecordCommand.kt:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at maestro.cli.DisableAnsiMixin$Companion.executionStrategy(DisableAnsiMixin.kt:22)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at maestro.cli.AppKt.main(App.kt:124)
```	

## Env

```
Maestro version: 1.22.1
OS: Mac OS X
OS version: 13.0.1
Architecture: aarch64
```

**Comment by ludwig-pro** [comment] 2023-02-13 18:59
expected behavior : 

https://user-images.githubusercontent.com/62896243/218549551-bea4d40a-7f3f-4ea6-b9a5-d5b688b2bb2a.mp4

**Comment by berikv** [comment] 2023-02-14 16:34
Hi Ludwig, Thank you very much for the clear error report!
Is it possible for you to share the app binary and flow file? You can share it with us privately if needed. Please drop me a line on Slack: https://docsend.com/view/3r2sf8fvvcjxvbtk

There is a fix for scrolling issues with bigger react native apps which was just merged into main. I'd like to test if your issue is also fixed there.

**Comment by ludwig-pro** [comment] 2023-02-14 17:00
Hey, thanks for your response and your amazing work ! 
I won't be able to give you the app binary of the app i'm working on (due to my client), but I will "try" to reproduce in a blank expo project (but I'm going on vacation tonight for two weeks :S I'll try ^^)

**Comment by berikv** [comment] 2023-02-14 17:25
Another option is for you to install the head maestro and see if the issue is fixed.
With homebrew the command is: `brew uninstall maestro; brew install --HEAD maestro-head`
To switch back to the release channel, run: `brew uninstall maestro-head; brew install maestro`

**Comment by ludwig-pro** [comment] 2023-02-14 21:19
humm  there is no available formula for maestro or maestro-head on brew 

`Warning: No available formula with the name "maestro-head".`

**Comment by ludwig-pro** [comment] 2023-02-14 23:32
I tried to reproduce with the blank react-native project and scrollable list on item... and everything works fine 🙈

**Comment by berikv** [comment] 2023-02-15 11:42
Aha, I forgot to mention, you need to first add our brew tap to be able to install maestro:
```
brew tap mobile-dev-inc/tap
brew install --HEAD maestro-head
```

Make sure to first uninstall the stable maestro using
```
cp ~/.maestro ~/.maestro_backup
```

The steps to go back to release channel are:
```
brew uninstall maestro-head
cp ~/.maestro_backup ~/.maestro
```

Thank you for your help!

**Comment by berikv** [comment] 2023-02-15 13:52
> I tried to reproduce with the blank react-native project and scrollable list on item... and everything works fine 🙈

To give some context on this issue:
ReactNative apps generally tend to have big view hierarchies. There is a bug in XCTest.framework that makes a test runner crash when the view hierarchy is above a certain size (its serialisation, in bytes).
To solve this issue I've started using XCTest's private API that does not depend on the view hierarchy. The recent changes made to maestro head implement scrolling using the private XCTest API, avoiding the XCTest.framework crash.

**Comment by berikv** [comment] 2023-02-15 14:10
Unfortunately the changes on scroll had to be reverted. I'll let you know when it is available.

**Comment by ludwig-pro** [comment] 2023-02-15 16:20
😱

> XCTest.framework that makes a test runner crash when the view hierarchy is above a certain size

ok! so I’m not surprised, I will try to have a look to the view hierarchy with Xcode, but I’m pretty sure, I will see a huge stack of view.

**Comment by berikv** [comment] 2023-02-15 16:48
Our goal is to not have a limit on view hierarchy and work around the issues of XCTest.framework. I am currently working to make that happen.

**Comment by AlexanderEggers** [comment] 2023-02-17 10:24
@berikv Just curious, do you have a rough idea when you think that fix might be available? I'm really keen to roll out maestro for my project but this issue is currently blocking that effort.

**Comment by berikv** [comment] 2023-02-17 16:06
I expect this issue to be fixed by the end of next week

**Comment by AlexanderEggers** [comment] 2023-02-21 12:15
@berikv That's great, thanks. If you need anyone to test the changes, let me know on this GH issue or ping me on the maestro slack space.

**Comment by berikv** [comment] 2023-02-23 16:40
Hi Alexander, today I've merged a fix for scrolling. If you could try it out before the next release I'd be very grateful.

**Comment by AlexanderEggers** [comment] 2023-02-24 01:35
@berikv I tried to checkout the maestro -head via the method you mentioned above and unfortuntely the gradle build is failing for me. Let me know if there another method for me to get the relevant snapshot pointing to the latest commit.

**Comment by dziter** [comment] 2023-03-02 11:27
@berikv : Same issue on my side like Alexander mentioned above I guess.
Command executed: arch -arm64 brew install --HEAD maestro-head --warning-mode all

<img width="1310" alt="Screenshot 2023-03-02 at 6 25 15 PM" src="https://user-images.githubusercontent.com/12848430/222415784-83b89567-c4f7-4a8a-a3ec-dec023375dee.png">

**Comment by berikv** [comment] 2023-03-02 11:44
@axelniklasson do you know what could cause this build failure?

**Comment by axelniklasson** [comment] 2023-05-30 11:52
Hi @ludwig-pro @AlexanderEggers, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!

**Closed by axelniklasson** 2023-05-30 11:52 UTC
Labels: bug, ios, needs-information, react-native
