### ISSUE TITLE
how to run .flow on windows 

### ISSUE THREAD

**Issue by periva101** [mobile-dev-inc/maestro#566] opened 2023-01-04 13:40 UTC
I followed the steps at https://maestro.mobile.dev/getting-started/installing-maestro/windows 
but I connected my android device with use debugging, the maestro is not finding my device,I think it is the same when I run the android emulator on windows.

the issue I cannot install android studio or run android emulator on Linux subsystem 

please help 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/52367616/210567308-757094a3-d482-46a7-8776-0b7ad92c6f42.png">

**Comment by uttamoffline** [comment] 2023-01-19 11:35
Hi @periva101 
I came across the same issue and please check if this discussion helps you. 
https://stackoverflow.com/questions/62145379/how-to-connect-android-studio-running-inside-wsl2-with-connected-devices-or-andr/63530375#63530375

**Comment by axelniklasson** [comment] 2023-05-03 14:04
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes to our [Windows installation documentation](https://maestro.mobile.dev/getting-started/installing-maestro/windows) since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:04 UTC
