### ISSUE TITLE
No devices available. To proceed, either install Android SDK or Xcode.

### ISSUE THREAD

**Issue by FunnyDevs** [mobile-dev-inc/maestro#581] opened 2023-01-10 14:06 UTC
Hello. 
I'm trying to use maestro on Ubuntu cli (WSL2) on Windows. I've installed all the necessary and i've created a symbolic link pointing to Windows adb.exe. 
All the adb commands work without problems.
If i start a maestro cli command i obtain the error " No devices available. To proceed, either install Android SDK or Xcode.".

Which it could be the problem?

Thank you

**Comment by GiwrgosMpartsas** [comment] 2023-01-26 15:47
i had the same problem and i found a solution that worked from me.
1) Open windows CMD and type adb devices
2) Type adb tcpip 5555
3) (Not neseccary) type adb connect 192.168.X.X:5555 (your device IP and without space :5555)
4) open ubuntu and type adb devices
5) type adb connect 192.168.X.X:5555 (again IP and without space :5555)

And now i guess if you type adb devices it suppose to be connected. if not, upload a screenshot if possible.

**Comment by FunnyDevs** [comment] 2023-01-31 15:04
I don't want to use the adb connection with tcp, i would like to use the adb exe from wsl.

**Comment by axelniklasson** [comment] 2023-05-03 14:16
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on our [Windows installation docs](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:16 UTC
