### ISSUE TITLE
[Maestro 1.36.0] It's not possible to specify a device when using Maestro on Windows.

### ISSUE THREAD

**Issue by mmalta24** [mobile-dev-inc/maestro#1736] opened 2024-05-08 11:10 UTC
**Describe the bug**
When attempting to run Maestro Studio or a YAML flow, it's not possible to specify the device. In Windows, it's necessary to set the host to run the Studio or a flow. However, despite setting the host, it seems to ignore the device specified in the command prompt and instead runs the flow or Studio on the first device registered on the ADB.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro --device emulator-5554 --host 10.0.0.76 studio`
3. The Studio does not display the device specified in the command.

**Environment information (please complete the following information):**

- Maestro version 1.36.0
- Platform: Android 14
- Framework: Native Android
- Device model and OS version: Google Pixel 6
- Physical device
- Host: Windows

**Comment by 7maucdn** [comment] 2024-07-12 16:13
I have also encountered this problem.

**Comment by bartekpacia** [comment] 2024-07-24 08:45
thanks @7maucdn 

closing as duplicate of #1799

**Closed by bartekpacia** 2024-07-24 08:45 UTC
Labels: bug
