### ISSUE TITLE
Maestro intermittently fails to execute steps in a flow

### ISSUE THREAD

**Issue by imGurpreetSK** [mobile-dev-inc/maestro#444] opened 2022-11-26 16:02 UTC
Preface: This has happened intermittently to me 3 times out of 11 runs.

Context: Certain steps are missed while executing a flow. For the flow attached alongwith, maestro failed to execute `tapOn: "Login"` command all 3 times.

Flow:
``` 
# Basic login flow

appId: com.jobget
---
  - launchApp
  - tapOn: "Login"
  - tapOn:
      text: "While using the app"
      optional: true
  - tapOn: "Continue as a job seeker"
  - tapOn: "Email address"
  - inputText: "gurpreetjs50@yopmail.com"
  - tapOn: "Password"
  - inputText: "Gurpreet@123#"
  - tapOn: "Login"
```

Attachment:

https://user-images.githubusercontent.com/11317262/204097807-3e6eb861-9f58-4ac3-b07a-9b12b7feb331.mov

**Comment by likeSo** [comment] 2022-11-27 05:45
I think maybe a `assertVisible: Login` command can resolve your problem. 
The `launchApp` command does not wait for your app launches to finish. So wait for it manually😂

**Comment by Leland-Takamine** [comment] 2023-05-03 13:56
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by Leland-Takamine** 2023-05-03 13:56 UTC
