### ISSUE TITLE
copyTextFrom always fails

### ISSUE THREAD

**Issue by japborst** [mobile-dev-inc/maestro#719] opened 2023-02-01 08:18 UTC
From the docs I gather that the input for `copyTextFrom` uses the same field find logic as all the other commands.

What works is running e.g. `assertVisible: "Name"`, but running the copy command `copyTextFrom: "Name"` does not.

Running a Flutter app, using maestro `1.21.3`

**Comment by vibin** [comment] 2023-02-26 12:50
For me, `copyTextFrom` is failing only in Studio. `maestro test` is running fine. Version: 1.23.0

**Comment by Leland-Takamine** [comment] 2023-05-03 14:04
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by Leland-Takamine** 2023-05-03 14:04 UTC
