### ISSUE TITLE
assertVisible and scrollUntilVisible do not work as expected in webviews

### ISSUE THREAD

**Issue by luethis** [mobile-dev-inc/maestro#704] opened 2023-01-29 19:33 UTC
**Description**
It looks like assertVisible and scrollUntilVisible do not respect visibility of ui elements in webviews as they are reported to be "visible" even if they are further down on the website. 

**Example script**

```
- openLink: https://en.wikipedia.org/wiki/Elton_John
- assertVisible: "Early life"
- scrollUntilVisible:
   element:
     text: "Early life"
   timeout: 10000
```

**Output** 
![Screenshot 2023-01-29 at 20 27 13](https://user-images.githubusercontent.com/36696579/215350965-2fec8c19-ae52-45f6-b263-cccd6471de5c.png)

**Expected Output**
Failed assertion 

(tested mainly on android, but i think iOS does not work either)

**Comment by luethis** [comment] 2023-01-29 19:34
could be related to https://github.com/mobile-dev-inc/maestro/pull/698

**Comment by axelniklasson** [comment] 2023-05-03 14:53
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:53 UTC
Labels: bug
