### ISSUE TITLE
Question: Flutter + WebViews

### ISSUE THREAD

**Issue by jakeBrightHR** [mobile-dev-inc/maestro#692] opened 2023-01-26 15:40 UTC
Couple of questions,

- Can Maestro handle WebViews within Flutter apps?
- Can Maestro handle native Android and iOS permission dialogs?

**Comment by Alpaca00** [comment] 2023-01-28 15:15
The first question @jakeBrightHR: it doesn't work for me,
the second question also has an interesting answer.

**Comment by bartekpacia** [comment] 2023-01-29 22:26
Hi @jakeBrightHR :)

Both use cases work in my simple, example app.

**Comment by jakeBrightHR** [comment] 2023-01-30 10:16
> The first question @jakeBrightHR: it doesn't work for me, the second question also has an interesting answer.

Haha, so what is the answer to the second question?

**Comment by amanjeetsingh150** [comment] 2023-02-03 07:20
Hey @jakeBrightHR answer to both of the questions should be yes, that is expected. If something doesn't work, can you open a separate issue for reproducing it. Closing this for now since the question is answered.

**Closed by amanjeetsingh150** 2023-02-03 07:20 UTC
