### ISSUE TITLE
Not resolved on windows at least even after installing 1.4.2

### ISSUE THREAD

**Issue by UnitedWithCode** [mobile-dev-inc/maestro#158] opened 2022-09-10 13:12 UTC
Not resolved on windows at least even after installing 1.4.2

D:\data\maestro\maestro-1.4.2\bin>adb devices
List of devices attached
emulator-5554   device

D:\data\maestro\maestro-1.4.2\bin>maestro test twitter.yaml
java.lang.IllegalStateException: No devices found. Select a platform by passing --platform <android|ios> for more details
        at maestro.cli.util.MaestroFactory.autoDetectPlatform(MaestroFactory.kt:68)
        at maestro.cli.util.MaestroFactory.createMaestro(MaestroFactory.kt:33)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:58)
        at maestro.cli.command.TestCommand.call(TestCommand.kt:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at maestro.cli.AppKt.main(App.kt:74)

_Originally posted by @astutesoftware in https://github.com/mobile-dev-inc/maestro/issues/123#issuecomment-1239304017_

**Comment by dmitry-zaitsev** [comment] 2022-09-13 11:42
Closing as a duplicate of #161 that has more comments on it

**Closed by dmitry-zaitsev** 2022-09-13 11:42 UTC
Labels: bug
