### ISSUE TITLE
'no android devices found'

### ISSUE THREAD

**Issue by ericmigi** [mobile-dev-inc/maestro#97] opened 2022-08-30 21:51 UTC
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1048265/187550070-4d643c11-058c-4e2d-b7af-a5880a3c17f2.png">

adb is connected. I can run `adb shell` no problem.

**Comment by Leland-Takamine** [comment] 2022-08-30 21:55
I know we verified that this was working last week, so something's going on. Let me test this flow out on my end.

**Comment by Leland-Takamine** [comment] 2022-08-30 22:02
Ok I'm running into the same issue with the pairing workflow. We'll investigate on our end. In the meantime, using an emulator seems to work fine. We'll report back when we've root caused the issue.

**Comment by Leland-Takamine** [comment] 2022-08-30 23:15
Alright this was due to a silly mistake in the documentation. We were missing step (2) below:

1. Pair your device over wifi using the standard `adb pair HOST:PORT CODE` command ([docs](https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+)).
    * eg: `adb pair 10.0.0.192:46851 123456`
2. Tell your device to listen for connections on port 5555.
    * `adb tcpip 5555`
3. Once your device is listening for connections on port 5555, Maestro can connect to your device using your device's IP address (same as HOST above).
    * eg: `maestro --host 10.0.0.192 test flow.yaml.`


I've updated the [documentation](https://maestro.mobile.dev/getting-started/installing-maestro#physical-device) as well.

@ericmigi Closing since I believe this is fixed with the update to the documentation, but please feel free to open back up if this still doesn't work for you!

**Closed by Leland-Takamine** 2022-08-30 23:15 UTC
