### ISSUE TITLE
[Bug] io.ktor.util.cio.ChannelWriteException: Cannot write to a channel

### ISSUE THREAD

**Issue by papaschmidt** [mobile-dev-inc/maestro#600] opened 2023-01-12 17:14 UTC
## Bug Description

Running `maestro studio` I am getting an exception in my terminal.  

## Environment
- M1 Pro MacOS 12.6.1
- Maestro 1.18.5 via brew

## Steps to reproduce
1. Just run `maestro studio`

## Actual Result

```
Running on iPhone 13 - iOS 15.2 
Waiting for idb service to start..
Waiting for Simulator to boot..
Waiting for successful taps
Simulator ready

╭────────────────────────────────────────────────────────╮
│                                                        │
│   Maestro Studio is running at http://localhost:9999   │
│                                                        │
╰────────────────────────────────────────────────────────╯


Note: Most Maestro CLI commands do not work while Maestro Studio is running. We will address this in an upcoming release.

Navigate to http://localhost:9999 in your browser to open Maestro Studio. Ctrl-C to exit.
io.ktor.util.cio.ChannelWriteException: Cannot write to a channel
	at io.ktor.server.netty.cio.NettyHttpResponsePipeline.respondWithFailure(NettyHttpResponsePipeline.kt:102)
	at io.ktor.server.netty.cio.NettyHttpResponsePipeline.respondWithBodyAndTrailerMessage(NettyHttpResponsePipeline.kt:252)
	at io.ktor.server.netty.cio.NettyHttpResponsePipeline.access$respondWithBodyAndTrailerMessage(NettyHttpResponsePipeline.kt:26)
	at io.ktor.server.netty.cio.NettyHttpResponsePipeline$respondWithBodyAndTrailerMessage$1.invokeSuspend(NettyHttpResponsePipeline.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda-1$lambda-0(NettyApplicationEngine.kt:288)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)                                                                                                                  
```

**Comment by axelniklasson** [comment] 2023-01-24 09:00
Hi @papaschmidt, thanks for reporting. If you try installing the latest version using the installation instructions outlined [here](https://maestro.mobile.dev/getting-started/installing-maestro#installing-the-cli), does this issue still persist?

```bash
curl -Ls "https://get.maestro.mobile.dev" | bash
```

**Comment by papaschmidt** [comment] 2023-01-24 13:17
@axelniklasson - I just upgraded to `1.19.5` and the issue still persists.

**Comment by papaschmidt** [comment] 2023-01-24 16:01
@axelniklasson - It would appear that other commands are working fine.  It is only `maestro studio` outputting the message in this issue.

**Comment by axelniklasson** [comment] 2023-02-13 10:47
@papaschmidt we are unable to reproduce this on our end and given that we haven't heard similar reports from other users this suggests issues with your local development environment. To confirm - did you also try installing `maestro` through the bash script or did you only use Homebrew?

**Comment by papaschmidt** [comment] 2023-02-14 10:08
> @papaschmidt we are unable to reproduce this on our end and given that we haven't heard similar reports from other users this suggests issues with your local development environment. To confirm - did you also try installing `maestro` through the bash script or did you only use Homebrew?

I have only tried it through home brew. I haven’t done it through the bash script.

**Comment by axelniklasson** [comment] 2023-02-14 10:13
@papaschmidt If you could try uninstalling it through brew and reinstalling through the bash script and see if that works that would be helpful. The bash script is the recommended installation method today so if there is an issue with Homebrew that would be very valuable to know so we can address it.

**Comment by papaschmidt** [comment] 2023-02-14 10:21
> @papaschmidt If you could try uninstalling it through brew and reinstalling through the bash script and see if that works that would be helpful. The bash script is the recommended installation method today so if there is an issue with Homebrew that would be very valuable to know so we can address it.

Hello,

I uninstalled it through brew and followed the installation steps in the docs. The same result.

**Comment by axelniklasson** [comment] 2023-05-03 14:19
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup since we are unable to reproduce this issue - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 14:19 UTC
