### ISSUE TITLE
[Maestro 1.34.1]: Button can be selected by text but fails when selected by testID

### ISSUE THREAD

**Issue by seyaobey-dev** [mobile-dev-inc/maestro#1594] opened 2023-11-19 03:13 UTC
**Describe the bug**
In my `react-native`, I have a `Signup button`. I can select the button by text but not by `testID`

This works:
```yaml
- tapOn: "sign up"
```

This fails:
```
- tapOn:
     id: "signup"
```

This is my very simple yaml file:

```
appId: com.user_name.app_name
---
- launchApp
- tapOn:
    id: "signup"
- tapOn: "full name"
- inputRandomPersonName
```

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. I followed instructions to install `maestro` on macos machine
2. I built my android app and installed the `.apk` in the emulator
3. I started the emulator
4. I ran `maestro test .master/sign-up.yaml`

**Expected behavior**
Button with testID `signupbtn` should be selected

**Environment information (please complete the following information):**

- Maestro version: 1.34.1
- Platform: Android 14
- Framework: React Native (Expo)
- Device model and OS version: Android 14
- Emulator
- Host: Mac M1

**Additional context**

**Comment by igorsmotto** [comment] 2023-11-20 15:24
Hi @seyaobey-dev!

I'm closing this as its not a bug.
Maestro is a black-box solution (not grey-box) as such it's impossible for it to have information about the TestID of your React Native code. Maestro only has visibility of the accessibility’s view hierarchy. 

You can use `maestro studio` to inspect what is actually visible in your screen from a user point of view.

**Closed by igorsmotto** 2023-11-20 15:24 UTC
Labels: bug
