### ISSUE TITLE
Maestro doesn't work with WSL 2

### ISSUE THREAD

**Issue by NinoDLC** [mobile-dev-inc/maestro#1851] opened 2024-07-30 14:16 UTC
Followed everything there : https://maestro.mobile.dev/getting-started/installing-maestro/windows

On powershell I have: 
```
C:\Work> adb -a -P 5037 nodaemon server
07-30 15:36:51.787 14820 14216 I adb.exe : auth.cpp:416 adb_auth_init...
07-30 15:36:51.792 14820 14216 I adb.exe : auth.cpp:152 loaded new key from 'C:\Users\Nino\.android\adbkey' with fingerprint <...>
07-30 15:36:51.792 14820  8748 I adb.exe : transport.cpp:338 emulator-5554: read thread spawning
07-30 15:36:51.793 14820 10548 I adb.exe : transport.cpp:310 emulator-5554: write thread spawning
07-30 15:36:51.802 14820 14216 I adb.exe : transport.cpp:1704 fetching keys for transport emulator-5554
07-30 15:36:51.802 14820 14216 I adb.exe : auth.cpp:468 Calling send_auth_response
07-30 15:36:51.820 14820 14216 I adb.exe : adb.cpp:180 emulator-5554: offline
```

Then on WSL 2 (Ubuntu 22.04), on another tab: 
```
C:\Work> wsl
nino@Desktino:/mnt/c/Work$ adb kill-server
cannot connect to daemon at tcp:5037: Connection refused
nino@Desktino:/mnt/c/Work$ export ADB_SERVER_SOCKET=tcp:192.168.1.10:5037
nino@Desktino:/mnt/c/Work$ adb devices
List of devices attached
emulator-5554   device

nino@Desktino:/mnt/c/Work$ cd lapresse/rubicon
nino@Desktino:/mnt/c/Work/lapresse/rubicon$ maestro --host 192.168.1.10 test -e APP_ID=ca.lapresse.android.lapressemobile.debug flows/run_flow.yaml

------------------ Shard 1 ------------------

Please specify a device platform [android, ios, web]:
android

Please specify Android version [34, 33, 31, 30, 29, 28]: Press ENTER for default (30)


Attempting to create Android emulator: Maestro_Pixel_6_API_30_1

Created Android emulator: Maestro_Pixel_6_API_30_1 (system-images;android-30;google_apis;x86_64)

❌ Error: BlockingCoroutine is cancelling
kotlinx.coroutines.JobCancellationException: BlockingCoroutine is cancelling; job=BlockingCoroutine{Cancelling}@28a65353
Caused by: maestro.cli.CliError: Unable to start device: Maestro_Pixel_6_API_30_1
        at maestro.cli.device.DeviceService.startDevice(DeviceService.kt:74)
        at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:237)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Note : 
* `192.168.1.10` is my local adress (found with `ipconfig` via Powershell), I don't know what is meant by "Note down the IPV4 address of your Windows host PC/machine." in the tutorial, but I guess this is it.  
* The test suite is already working on MacOS (they are running the command without the `--host` param)
* I tried with an Android 35 emulator, and then with an Android 30 emulator, to no avail.

**Comment by bartekpacia** [comment] 2024-07-31 12:16
Hi @NinoDLC, thanks a lot for this bug report. Could you please adapt it to follow [the bug report template](https://github.com/mobile-dev-inc/maestro/issues/new/choose)? You can create a new issue, paste existing stuff, and fill out fields that are missing. Thank you.

**Comment by bartekpacia** [comment] 2024-08-09 13:41
Closing as a very likely duplicate of #1863

**Closed by bartekpacia** 2024-08-09 13:41 UTC
Labels: waiting for customer response, host: windows-wsl
