### ISSUE TITLE
Flutter BottomNavBarItem cannot be found [Maestro V1.27.0]

### ISSUE THREAD

**Issue by Meesen** [mobile-dev-inc/maestro#1069] opened 2023-05-13 22:04 UTC
**Describe the bug**
TapOn does not seem to find BottomNavBarItems

**To Reproduce**
Add a BottomNavBar to the scaffold 
add an icon and a label or semantics around the icon 
setup the test trying to tap on a button

**Expected behavior**
it should be able to navigate/find the icon
does not seem to be able to

**Screenshots**
(you can see in the screenshot below i have wrapped the icon widget of the bottomnavbaritem with semantics and tried alot of options none of which seems to work)
![image](https://github.com/mobile-dev-inc/maestro/assets/32506712/4bbbf767-282a-43c8-923c-db7aeedc2485)

**Environment information (please complete the following information):**

- Maestro V1.27.0
- Platform:  Android 11.0
- Framework: Flutter
- Device model and OS version: Pixel 6 pro
- Simulator, emulator 
- Host: Windows

**Comment by igorsmotto** [comment] 2023-05-16 19:33
Hey @Meesen, thanks for reporting this.
 
Could you try running `maestro studio` and see if there is a different way to select each item? 
I suspect the issue is how the `Semantics` key of the icon is being merged to the title and probably other metadata to the `BottomNavigationBarItem`.

**Comment by Meesen** [comment] 2023-05-16 21:29
hey @igorsmotto, thank you for the response, I've looked in to how it looks in maestro studio and if I use the tag it's giving me it seems to work. 
I only had the semantics widget because I read that it might help find it.

without the semantics the menu BottomNavbarItem works with: tapOn: 'Menu\nTab 2 of 2'

sorry to bother you, I had seens maestro studio on your website before but I forbot it was a thing.

anyway thank you for your help

**Closed** 2023-05-16 21:35 UTC
Labels: bug, android, flutter
