### ISSUE TITLE
Maestro studio suddenly stops working

### ISSUE THREAD

**Issue by carlosfiori** [mobile-dev-inc/maestro#716] opened 2023-01-31 19:54 UTC
I'm getting this error after interacting few times in meters studio. This error is happening on Android (device and emulator) and iOS

```
assertion failed [found_x86_offset]: no instruction entry found for jit breakpoint at arm address 0x10c0ec8c0
(TranslationCacheJit.cpp:300 handle_jit_breakpoint)
[1]    23628 trace trap  maestro studio
```

![image](https://user-images.githubusercontent.com/20682772/215867410-9b40f1da-d377-4acf-9894-12d147b59aff.png)

**Comment by axelniklasson** [comment] 2023-05-03 15:01
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro Studio since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 15:01 UTC
