### ISSUE TITLE
Click on element(button) is not working .

### ISSUE THREAD

**Issue by Harish30594** [mobile-dev-inc/maestro#424] opened 2022-11-18 05:11 UTC
Facing issue while clicking on  "Proceed to Pay" button in Swiggy  App.
I have attached the screenshot of execution  and maestro hierarchy .

**screenshot of code and app :**
<img width="1747" alt="Screenshot 2022-11-17 at 3 53 06 PM" src="https://user-images.githubusercontent.com/26534319/202622699-7e0e45ec-03cd-4ec0-8975-e085835f214b.png">

**maestro hierarchy :**
[hierchy_output_check.txt](https://github.com/mobile-dev-inc/maestro/files/10037948/hierchy_output_check.txt)

**App:**
https://swiggy.en.uptodown.com/android/download

**Comment by Leland-Takamine** [comment] 2023-05-03 13:48
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues, please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by Leland-Takamine** 2023-05-03 13:48 UTC
