### ISSUE TITLE
scrollUntilVisible doesn't work anymore on Android in Maestro 1.21.3

### ISSUE THREAD

**Issue by apaolino** [mobile-dev-inc/maestro#712] opened 2023-01-30 19:24 UTC
Hi,
I had a test containing a scrollUntilVisible command (scrolling up until a specific text is visible) and after I've upgraded to 1.21.3 it doesn't complete anymore. It just keeps scrolling up on Android.

After downgrading to 1.21.2 it works again.

**Comment by ArthurSav** [comment] 2023-01-31 05:59
Thanks for reporting @apaolino . Will take a look

**Comment by axelniklasson** [comment] 2023-05-03 15:02
Thanks for taking the time to raise this issue! There has been a lot of improvements and fixes on Maestro and `scrollUntilVisible` since this was raised so we’ll go ahead and close this one out as part of an issue cleanup - if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!

**Closed by axelniklasson** 2023-05-03 15:02 UTC
